APP.renderShell = () => renderShell();
APP.home = '/overview';
APP.actor = 'Admin Pusat';
APP.renderSide = () => renderSide();
APP.renderTop = () => renderTop();
APP.renderBanners = () => renderBanners();
APP.accountMenu = () => acctHTML();
APP.closeContext = () => { if (OMNI.showCtx && A['ctx-toggle']) A['ctx-toggle'](); };
APP.afterPoll = () => { const ol = document.getElementById('omni-live'); if (ol && typeof omniLoad === 'function') omniLoad(ol.dataset.ch).catch(() => {}); };
APP.conversationChanged = a => { if (OMNI.active !== a.id) return; const ch = document.getElementById('chat'); if (ch) setTimeout(() => { const x = document.getElementById('chat'); if (x) x.scrollTop = x.scrollHeight; }, 50); };
