/* ======================= CONTROL CENTER REGISTRY ======================= */
registerRoles({
  super_admin: { label: 'Super Admin', perms: ['*'] },
  compliance: { label: 'Compliance Officer', perms: ['overview.view', 'approval.view', 'approval.decide:legal', 'approval.decide:travel', 'approval.decide:vendor', 'approval.decide:security', 'travel.*', 'vendor.*', 'affiliate.view', 'mitra.view', 'compliance.*', 'audit.view', 'iamap.view'] },
  finance_ops: { label: 'Finance Ops', perms: ['overview.view', 'approval.view', 'approval.decide:finance', 'finance.*', 'booking.view', 'travel.view', 'travel.finance', 'saas.view', 'audit.view', 'iamap.view'] },
  cs_agent: { label: 'CS Agent', perms: ['overview.view', 'omni.*', 'booking.view', 'traveler.view', 'travel.view', 'iamap.view'] }
});
registerNav([
 { g: 'g_utama', items: [{ id: 'overview', r: '/overview', i: 'home', p: 'overview.view', lvl: 'hi' }, { id: 'approval', r: '/approval', i: 'approval', p: 'approval.view', lvl: 'hi', badge: () => APPROVALS.filter(a => a.status === 'waiting' || a.status === 'in_progress').length, alert: true }] },
 { g: 'g_eko', items: [
   { id: 'travel', i: 'building', p: 'travel.view', kids: [{ id: 'travel_all', r: '/travel', lvl: 'hi' }, { id: 'travel_branch', r: '/travel/branches', lvl: 'md' }, { id: 'travel_legal', r: '/travel/legal', lvl: 'md', badge: () => TRAVELS.filter(x => x.legal === 'under_review').length }, { id: 'travel_subs', r: '/travel/subscription', lvl: 'md' }, { id: 'travel_web', r: '/travel/website', lvl: 'ph' }] },
   { id: 'vendor', i: 'store', p: 'vendor.view', kids: [{ id: 'vendor_all', r: '/vendor', lvl: 'md' }, { id: 'vendor_cat', r: '/vendor/categories', lvl: 'ph' }, { id: 'vendor_verif', r: '/vendor/verification', lvl: 'md', badge: () => VENDORS.filter(v => v.verif !== 'verified' && v.verif !== 'rejected').length }, { id: 'vendor_prod', r: '/vendor/products', lvl: 'ph' }] },
   { id: 'affiliate', i: 'link', p: 'affiliate.view', kids: [{ id: 'aff_all', r: '/affiliate', lvl: 'md' }, { id: 'aff_ref', r: '/affiliate/referral', lvl: 'ph' }, { id: 'aff_com', r: '/affiliate/commission', lvl: 'ph' }, { id: 'aff_perf', r: '/affiliate/performance', lvl: 'ph' }] },
   { id: 'mitra', r: '/mitra', i: 'users', p: 'mitra.view', lvl: 'md' },
   { id: 'agen', r: '/agen', i: 'user', p: 'mitra.view', lvl: 'md' },
   { id: 'traveler', r: '/traveler', i: 'user', p: 'traveler.view', lvl: 'md' }] },
 { g: 'g_mp', items: [{ id: 'mp_ov', r: '/marketplace', i: 'bag', p: 'marketplace.view', lvl: 'ph' }, { id: 'mp_pkg', r: '/marketplace/packages', i: 'package', p: 'marketplace.view', lvl: 'md' }, { id: 'mp_vprod', r: '/marketplace/vendor-products', i: 'store', p: 'marketplace.view', lvl: 'ph' }, { id: 'segadeals', r: '/marketplace/segadeals', i: 'tag', p: 'marketplace.view', lvl: 'ph' }, { id: 'mp_rev', r: '/marketplace/reviews', i: 'star', p: 'marketplace.view', lvl: 'ph' }, { id: 'mp_cat', r: '/marketplace/categories', i: 'grid', p: 'marketplace.view', lvl: 'ph' }, { id: 'mp_mod', r: '/marketplace/moderation', i: 'shieldc', p: 'marketplace.view', lvl: 'ph', badge: () => PACKAGES.filter(p => p.state === 'review').length }] },
 { g: 'g_omni', items: [{ id: 'om_ov', r: '/omni', i: 'radio', p: 'omni.view', lvl: 'ph' }, { id: 'om_inbox', r: '/omni/inbox', i: 'inbox', p: 'omni.view', lvl: 'hi', badge: () => CONVERSATIONS.filter(c => c.unread > 0).length, alert: true }, { id: 'om_conv', r: '/omni/conversations', i: 'msg', p: 'omni.view', lvl: 'md' },
   { id: 'om_chan', i: 'radio', p: 'omni.view', kids: [{ id: 'om_app', r: '/omni/channel/aplikasi', lvl: 'md' }, { id: 'om_dash', r: '/omni/channel/dashboard', lvl: 'md' }, { id: 'om_push', r: '/omni/channel/push', lvl: 'ph' }, { id: 'om_wa', r: '/omni/channel/whatsapp', lvl: 'hi' }, { id: 'om_ig', r: '/omni/channel/instagram', lvl: 'hi' }, { id: 'om_fb', r: '/omni/channel/facebook', lvl: 'hi' }, { id: 'om_email', r: '/omni/channel/email', lvl: 'hi' }, { id: 'om_tg', r: '/omni/channel/telegram', lvl: 'hi' }, { id: 'om_web', r: '/omni/channel/webchat', lvl: 'md' }] },
   { id: 'om_contact', r: '/omni/contacts', i: 'users', p: 'omni.view', lvl: 'ph' }, { id: 'om_tpl', r: '/omni/templates', i: 'filetext', p: 'omni.view', lvl: 'ph' }, { id: 'om_bc', r: '/omni/broadcast', i: 'megaphone', p: 'omni.view', lvl: 'ph' }, { id: 'om_auto', r: '/omni/automation', i: 'zap', p: 'omni.view', lvl: 'ph' }, { id: 'om_route', r: '/omni/routing', i: 'route', p: 'omni.view', lvl: 'ph' }, { id: 'om_sla', r: '/omni/sla', i: 'timer', p: 'omni.view', lvl: 'ph' }, { id: 'om_ana', r: '/omni/analytics', i: 'chart', p: 'omni.view', lvl: 'ph' }] },
 { g: 'g_ads', items: [{ id: 'ads_ov', r: '/ads', i: 'megaphone', p: 'ads.view', lvl: 'hi' }, { id: 'ads_camp', r: '/ads/campaigns', i: 'target', p: 'ads.view', lvl: 'md', badge: () => CAMPAIGNS.filter(c => c.state === 'review').length }, { id: 'ads_ads', r: '/ads/ads', i: 'image', p: 'ads.view', lvl: 'ph' }, { id: 'ads_set', r: '/ads/adsets', i: 'layers', p: 'ads.view', lvl: 'ph' }, { id: 'ads_cre', r: '/ads/creative', i: 'image', p: 'ads.view', lvl: 'ph' }, { id: 'ads_plc', r: '/ads/placement', i: 'grid', p: 'ads.view', lvl: 'ph' }, { id: 'ads_bud', r: '/ads/budget', i: 'wallet', p: 'ads.view', lvl: 'ph' }, { id: 'ads_vou', r: '/ads/voucher', i: 'ticket', p: 'ads.view', lvl: 'ph' }, { id: 'ads_trk', r: '/ads/tracking', i: 'crosshair', p: 'ads.view', lvl: 'ph' }, { id: 'ads_conv', r: '/ads/conversion', i: 'funnel', p: 'ads.view', lvl: 'ph' }, { id: 'ads_attr', r: '/ads/attribution', i: 'branch', p: 'ads.view', lvl: 'ph' }, { id: 'ads_perf', r: '/ads/performance', i: 'trend', p: 'ads.view', lvl: 'ph' }] },
 { g: 'g_book', items: [{ id: 'booking', r: '/booking', i: 'calendar', p: 'booking.view', lvl: 'md' }, { id: 'manifest', r: '/booking/manifest', i: 'list', p: 'booking.view', lvl: 'ph' }, { id: 'roomlist', r: '/booking/rooms', i: 'bed', p: 'booking.view', lvl: 'ph' }, { id: 'pkginfo', r: '/booking/package-info', i: 'info', p: 'booking.view', lvl: 'ph' }, { id: 'opsdoc', r: '/booking/documents', i: 'folder', p: 'booking.view', lvl: 'ph' }] },
 { g: 'g_fin', items: [{ id: 'fin_ov', r: '/finance', i: 'wallet', p: 'finance.view', lvl: 'hi' }, { id: 'fin_tx', r: '/finance/transactions', i: 'repeat', p: 'finance.view', lvl: 'md' }, { id: 'fin_pg', r: '/finance/gateway', i: 'card', p: 'finance.view', lvl: 'ph' }, { id: 'fin_set', r: '/finance/settlement', i: 'landmark', p: 'finance.view', lvl: 'md' }, { id: 'fin_wd', r: '/finance/withdrawal', i: 'arrowur', p: 'finance.view', lvl: 'md', badge: () => WITHDRAWALS.filter(w => w.state === 'pending').length, alert: true }, { id: 'fin_dep', r: '/finance/deposit', i: 'download', p: 'finance.view', lvl: 'ph' }, { id: 'fin_ref', r: '/finance/refund', i: 'undo', p: 'finance.view', lvl: 'md', badge: () => REFUNDS.filter(r => r.state === 'pending').length }, { id: 'fin_rec', r: '/finance/reconciliation', i: 'scale', p: 'finance.view', lvl: 'ph' }, { id: 'fin_fee', r: '/finance/fee', i: 'percent', p: 'finance.view', lvl: 'ph' }] },
 { g: 'g_saas', items: [{ id: 'sub', r: '/saas/subscription', i: 'refresh', p: 'saas.view', lvl: 'md' }, { id: 'plan', r: '/saas/plans', i: 'grid', p: 'saas.view', lvl: 'ph' }, { id: 'addon', r: '/saas/addons', i: 'plussq', p: 'saas.view', lvl: 'ph' }, { id: 'website', r: '/saas/website', i: 'globe', p: 'saas.view', lvl: 'ph' }, { id: 'crm', r: '/saas/crm', i: 'crm', p: 'saas.view', lvl: 'ph' }] },
 { g: 'g_plat', items: [{ id: 'users', r: '/platform/users', i: 'users', p: 'platform.view', lvl: 'ph' }, { id: 'roles', r: '/platform/roles', i: 'lock', p: 'platform.view', lvl: 'ph' }, { id: 'notif', r: '/platform/notification', i: 'bell', p: 'platform.view', lvl: 'ph' }, { id: 'ai', r: '/platform/ai', i: 'sparkles', p: 'platform.view', lvl: 'ph' }] },
 { g: 'g_comp', items: [{ id: 'legal', r: '/compliance/legal', i: 'filecheck', p: 'compliance.view', lvl: 'md' }, { id: 'audit', r: '/compliance/audit', i: 'history', p: 'audit.view', lvl: 'md' }, { id: 'security', r: '/compliance/security', i: 'shield', p: 'compliance.view', lvl: 'ph' }, { id: 'risk', r: '/compliance/risk', i: 'alert', p: 'compliance.view', lvl: 'ph' }] },
 { g: 'g_ana', items: [{ id: 'an_exec', r: '/analytics/executive', i: 'chart', p: 'analytics.view', lvl: 'ph' }, { id: 'an_mp', r: '/analytics/marketplace', i: 'bag', p: 'analytics.view', lvl: 'ph' }, { id: 'an_travel', r: '/analytics/travel', i: 'building', p: 'analytics.view', lvl: 'ph' }, { id: 'an_vendor', r: '/analytics/vendor', i: 'store', p: 'analytics.view', lvl: 'ph' }, { id: 'an_fin', r: '/analytics/finance', i: 'wallet', p: 'analytics.view', lvl: 'ph' }, { id: 'an_omni', r: '/analytics/omnichannel', i: 'msg', p: 'analytics.view', lvl: 'ph' }, { id: 'an_ads', r: '/analytics/ads', i: 'megaphone', p: 'analytics.view', lvl: 'ph' }, { id: 'an_camp', r: '/analytics/campaign', i: 'target', p: 'analytics.view', lvl: 'ph' }, { id: 'an_conv', r: '/analytics/conversion', i: 'branch', p: 'analytics.view', lvl: 'ph' }, { id: 'an_growth', r: '/analytics/growth', i: 'trend', p: 'analytics.view', lvl: 'ph' }] },
 { g: 'g_sys', items: [{ id: 'sys_cfg', r: '/system/config', i: 'sliders', p: 'system.view', lvl: 'ph' }, { id: 'sys_brand', r: '/system/brand', i: 'palette', p: 'system.view', lvl: 'md' }, { id: 'sys_lang', r: '/system/language', i: 'languages', p: 'system.view', lvl: 'ph' }, { id: 'sys_cur', r: '/system/currency', i: 'banknote', p: 'system.view', lvl: 'ph' }, { id: 'sys_pay', r: '/system/payment', i: 'card', p: 'system.view', lvl: 'ph' }, { id: 'sys_ncfg', r: '/system/notification', i: 'bell', p: 'system.view', lvl: 'ph' }, { id: 'sys_flag', r: '/system/flags', i: 'toggle', p: 'system.view', lvl: 'ph' }, { id: 'sys_int', r: '/system/integration', i: 'plug', p: 'system.view', lvl: 'ph' }, { id: 'sys_health', r: '/system/health', i: 'activity', p: 'system.view', lvl: 'ph' }] }
]);

function navBadge(n) { if (!n.badge) return ''; const v = n.badge(); if (!v) return ''; return `<span class="nbadge ${n.alert ? 'alert' : 'count'}" aria-label="${v} item">${v}</span>`; }
function renderSide() {
  const act = activeNavId(S.route), an = NAVIDX[act]; const f = S.navFilter.toLowerCase();
  const match = n => !f || t(n.id).toLowerCase().includes(f) || (n.kids || []).some(k => t(k.id).toLowerCase().includes(f));
  let h = `<div class="side-head"><div class="brandmark" style="--brand:${BRAND.color}">${esc(BRAND.mark)}</div><div class="brandtext"><div class="brandname">${esc(BRAND.name)}</div><div class="brandsub">${esc(t('control_center'))}</div></div></div>
  <div class="side-filter">${ic('search', 'sm')}<input id="navfilter" type="search" placeholder="${esc(t('filter_menu'))}" value="${esc(S.navFilter)}" aria-label="${esc(t('filter_menu'))}"></div>
  <nav class="side-scroll" id="sidenav">`;
  NAV.forEach(g => {
    const items = g.items.filter(m => can(m.p) && match(m)); if (!items.length) return;
    const hasActive = items.some(m => m.id === act || (an && an.parent === m));
    const open = f || S.openG.has(g.g) || (hasActive && !S.openG.has('__x' + g.g)); const alertSum = items.reduce((s, m) => s + (m.alert && m.badge ? m.badge() : 0), 0);
    h += `<div class="nav-group"><button class="nav-gbtn" data-act="tg-group" data-g="${g.g}" aria-expanded="${open}"><span class="gl">${esc(t(g.g))}</span>${!open && alertSum ? `<span class="gcount">${alertSum}</span>` : ''}${ic('chevD', 'sm chev')}</button>`;
    if (open) {
      h += `<ul class="nav-list">`;
      items.forEach(m => {
        if (m.kids) {
          const kidAct = an && an.parent === m; const mo = f || S.openM.has(m.id) || (kidAct && !S.openM.has('__x' + m.id)); const kb = m.kids.reduce((s, k) => s + (k.badge ? k.badge() : 0), 0);
          h += `<li><button class="nav-item ${kidAct ? 'parent-active' : ''}" data-act="tg-mod" data-m="${m.id}" aria-expanded="${mo}" data-label="${esc(t(m.id))}" data-fly="${m.id}">${ic(m.i)}<span class="lbl">${esc(t(m.id))}</span>${!mo && kb ? `<span class="nbadge count">${kb}</span>` : ''}${kb ? '<i class="dot"></i>' : ''}${icd('chevR', 'sm chev')}</button>`;
          if (mo) h += `<ul class="nav-sub">${m.kids.filter(k => !f || t(k.id).toLowerCase().includes(f) || t(m.id).toLowerCase().includes(f)).map(k => `<li><a class="nav-item ${k.id === act ? 'active' : ''}" href="#${k.r}" ${k.id === act ? 'aria-current="page"' : ''}><span class="lbl">${esc(t(k.id))}</span>${navBadge(k)}${k.lvl === 'ph' ? `<span class="nbadge soon" title="${esc(t('lvl_ph'))}">IA</span>` : ''}</a></li>`).join('')}</ul>`;
          h += `</li>`;
        } else {
          h += `<li><a class="nav-item ${m.id === act ? 'active' : ''}" href="#${m.r}" data-label="${esc(t(m.id))}" ${m.id === act ? 'aria-current="page"' : ''}>${ic(m.i)}<span class="lbl">${esc(t(m.id))}</span>${navBadge(m)}${m.badge && m.badge() && m.alert ? '<i class="dot"></i>' : ''}${m.lvl === 'ph' ? `<span class="nbadge soon" title="${esc(t('lvl_ph'))}">IA</span>` : ''}</a></li>`;
        }
      });
      h += `</ul>`;
    }
    h += `</div>`;
  });
  h += `</nav><div class="side-foot"><a class="nav-item ${act === 'iamap' ? 'active' : ''}" href="#/ia" data-label="${esc(t('iamap'))}">${ic('grid')}<span class="lbl">${esc(t('iamap'))}</span></a><button class="iconbtn desk-only" style="color:var(--side-ink-2)" data-act="collapse" aria-label="${esc(S.collapsed ? t('expand') : t('collapse'))}" data-label="${esc(S.collapsed ? t('expand') : t('collapse'))}">${ic('panel')}</button></div>`;
  const side = document.getElementById('side'); const sc = side.querySelector('.side-scroll'); const top = sc ? sc.scrollTop : 0; side.innerHTML = h; side.querySelector('.side-scroll').scrollTop = top;
  const fi = document.getElementById('navfilter'); fi.addEventListener('input', e => { S.navFilter = e.target.value; renderSide(); const n = document.getElementById('navfilter'); n.focus(); n.setSelectionRange(n.value.length, n.value.length); });
}


/* ======================= CONTROL CENTER ACTIONS ======================= */
Object.assign(A, {
  /* tables */
  'tbl-f': el => { const T = TBL[el.dataset.tbl]; T.fval = el.dataset.v; T.page = 1; refreshTable(el.dataset.tbl); },
  'tbl-sort': el => { const T = TBL[el.dataset.tbl]; if (T.sortK === el.dataset.k) T.sortDir *= -1; else { T.sortK = el.dataset.k; T.sortDir = 1; } refreshTable(el.dataset.tbl); },
  'tbl-pg': el => { TBL[el.dataset.tbl].page = +el.dataset.p; refreshTable(el.dataset.tbl); document.getElementById('tb-' + el.dataset.tbl).scrollIntoView({ block: 'nearest' }); },
  'tbl-sel': el => { const T = TBL[el.dataset.tbl]; el.checked ? T.sel.add(el.dataset.id) : T.sel.delete(el.dataset.id); refreshTable(el.dataset.tbl); },
  'tbl-selall': el => { const T = TBL[el.dataset.tbl]; const rows = tblRows(el.dataset.tbl).slice((T.page - 1) * T.size, T.page * T.size); rows.forEach(r => el.checked ? T.sel.add(r.id) : T.sel.delete(r.id)); refreshTable(el.dataset.tbl); },
  'tbl-clear': el => { TBL[el.dataset.tbl].sel.clear(); refreshTable(el.dataset.tbl); },
  'tbl-reset': el => { const T = TBL[el.dataset.tbl]; T.q = ''; T.fval = 'all'; T.page = 1; if (el.dataset.tbl === 'travel') Object.keys(TRX).forEach(k => TRX[k] = 'all'); refreshTable(el.dataset.tbl); },
  'tbl-cols': el => { const T = TBL[el.dataset.tbl]; popAt(el, `<div class="menu"><div class="mh">${t('columns')}</div>${T.cols.filter(c => c.k !== 'act').map((c, i) => `<button class="mi" role="menuitemcheckbox" aria-checked="${!T.hidden.has(c.k)}" data-act="tbl-colt" data-tbl="${el.dataset.tbl}" data-k="${c.k}" ${i === 0 ? 'disabled style="opacity:.6"' : ''}>${esc(c.label)}</button>`).join('')}</div>`); },
  'tbl-colt': el => { const T = TBL[el.dataset.tbl]; T.hidden.has(el.dataset.k) ? T.hidden.delete(el.dataset.k) : T.hidden.add(el.dataset.k); el.setAttribute('aria-checked', !T.hidden.has(el.dataset.k)); refreshTable(el.dataset.tbl); },
  bulk: el => { const T = TBL[el.dataset.tbl]; const n = T.sel.size; if (el.dataset.b === 'suspend') { confirmAction({ title: L3(['Suspend ', 'Suspend ', 'تعليق ']) + n + ' Travel', desc: L3(['Tenant tidak dapat menerima booking baru; paket di-unpublish sementara. Booking berjalan tetap dilayani.', 'Tenants cannot receive new bookings; packages are temporarily unpublished. Existing bookings continue.', 'لن تستقبل الشركات حجوزات جديدة.']), tone: 'danger', label: 'Suspend', resource: [...T.sel].join(', '), onOk: r => { [...T.sel].forEach(id => { const x = travelById(id); if (x) { x.op = 'inactive'; audit('Admin Pusat', 'travel.suspend', 'Travel/' + id, 'success', { reason: r }); } }); T.sel.clear(); toast('ok', n + ' Travel suspended', L3(['Tercatat di audit', 'Recorded in audit', 'مسجل']), '/compliance/audit'); rerender(); } }); return; } toast('ok', (el.dataset.b === 'export' ? 'Export ' : L3(['Pengingat dikirim ke ', 'Reminder sent to ', 'أُرسل تذكير إلى '])) + n + ' item', el.dataset.b === 'export' ? L3(['File CSV disiapkan di server — link unduhan dikirim via notifikasi.', 'CSV is prepared server-side — download link sent via notification.', 'يُعد الملف على الخادم.']) : 'WhatsApp + Email'); T.sel.clear(); refreshTable(el.dataset.tbl); },
  export: el => toast('info', 'Export · ' + el.dataset.what, L3(['Export dijalankan di server (menghormati permission & filter aktif). Link dikirim ke Notifikasi.', 'Export runs server-side (respecting permissions & active filters). Link will arrive in Notifications.', 'يتم التصدير على الخادم.'])),
  'more-filter': el => { const sel = (id, k, opts) => `<div class="field"><label for="${id}">${esc(k[1])}</label><select id="${id}">${opts.map(o => `<option value="${esc(o[0])}" ${TRX[k[0]] === o[0] ? 'selected' : ''}>${esc(o[1])}</option>`).join('')}</select></div>`; modal({ title: t('filters_more'), body: `<div class="grid g2" style="gap:10px">${sel('mf-plan', ['plan', 'Plan'], [['all', t('all')], ['Starter', 'Starter'], ['Growth', 'Growth'], ['Scale', 'Scale']])}${sel('mf-legal', ['legal', t('c_legal')], [['all', t('all')], ...['verified', 'expiring', 'under_review', 'expired', 'rejected'].map(s => [s, L3(STATUS[s].slice(2))])])}${sel('mf-pay', ['pay', 'Payment flow'], [['all', t('all')], ['VIA_SEGALOKA', 'VIA_SEGALOKA'], ['DIRECT_TO_TRAVEL', 'DIRECT_TO_TRAVEL']])}${sel('mf-city', ['city', L3(['Kota', 'City', 'المدينة'])], [['all', t('all')], ...CITIES.map(c => [c[0], c[0]])])}</div>`, foot: `<button class="btn ghost" data-act="mf-reset">${t('reset_filters')}</button><span style="flex:1"></span><button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="mf-apply">${L3(['Terapkan', 'Apply', 'تطبيق'])}</button>` }); },
  'mf-apply': () => { TRX.plan = document.getElementById('mf-plan').value; TRX.legal = document.getElementById('mf-legal').value; TRX.pay = document.getElementById('mf-pay').value; TRX.city = document.getElementById('mf-city').value; closeOverlays(); TBL.travel.page = 1; refreshTable('travel'); const n = Object.values(TRX).filter(v => v !== 'all').length; if (n) toast('info', n + ' ' + L3(['filter tambahan aktif', 'extra filters active', 'مرشحات إضافية']), Object.entries(TRX).filter(e => e[1] !== 'all').map(e => e[0] + ': ' + e[1]).join(' · ')); },
  'mf-reset': () => { Object.keys(TRX).forEach(k => TRX[k] = 'all'); closeOverlays(); refreshTable('travel'); },
  'preview-data': () => modal({ title: t('preview'), wide: true, body: `<p class="muted" style="margin-top:0">${L3(['Pratinjau 5 baris pertama sesuai filter aktif — format yang akan diexport.', 'Preview of the first 5 rows under active filters — the export format.', 'معاينة أول 5 صفوف.'])} ${mockmark()}</p><div class="tbl-wrap"><table class="t"><thead><tr>${['travel_id', 'name', 'city', 'licenses', 'legal_status', 'subscription', 'branches', 'payment_flow', 'status'].map(h => `<th class="mono">${h}</th>`).join('')}</tr></thead><tbody>${tblRows('travel').slice(0, 5).map(r => `<tr class="mono" style="font-size:12px"><td>${r.id}</td><td>${esc(r.name)}</td><td>${esc(r.city)}</td><td>${r.lic.map(l => l.type + ':' + l.status).join('|')}</td><td>${r.legal}</td><td>${r.sub.plan}:${r.sub.state}</td><td>${r.branch.used}/${r.branch.quota}</td><td>${r.payMode}</td><td>${r.op}</td></tr>`).join('')}</tbody></table></div>`, foot: `<button class="btn" data-act="close">${t('close')}</button><button class="btn primary" data-act="export" data-what="Travel">${ic('download')}${t('export')}</button>` }),
  'row-menu': el => { const x = travelById(el.dataset.id); popAt(el, `<div class="menu"><div class="mh">${esc(x.name)}</div>${[['eye', t('open_detail'), '/travel/' + x.id], ['filecheck', t('t_legal'), '/travel/' + x.id + '/legal'], ['refresh', t('t_sub'), '/travel/' + x.id + '/subscription'], ['calendar', t('t_book'), '/travel/' + x.id + '/booking'], ['history', t('t_act'), '/travel/' + x.id + '/activity']].map(m => `<button class="mi" data-act="nav" data-r="${m[2]}">${ic(m[0], 'sm')}${esc(m[1])}</button>`).join('')}<div class="sep"></div><button class="mi" data-act="copy" data-v="${x.id}">${ic('copy', 'sm')}Copy Travel ID</button>${can('travel.suspend') ? `<button class="mi" data-act="travel-status" data-id="${x.id}" data-v="${x.op === 'inactive' ? 'active' : 'inactive'}" style="color:var(--${x.op === 'inactive' ? 'ok' : 'bad'})">${ic(x.op === 'inactive' ? 'play' : 'ban', 'sm')}${x.op === 'inactive' ? t('reactivate') : t('suspend')}</button>` : `<button class="mi" aria-disabled="true" style="opacity:.5">${ic('lock', 'sm')}${t('suspend')} · ${t('no_perm_action')}</button>`}</div>`); },
  'add-travel': () => openAddTravel(),
  'add-travel-save': () => { const n = document.getElementById('nt-name').value.trim(); if (!n) { const f = document.getElementById('nt-name'); f.focus(); f.style.borderColor = 'var(--bad)'; return; } const id = 'TRV-' + (12000 + TRAVELS.length * 7); const city = document.getElementById('nt-city').value; const lic = [{ type: 'BPW', no: '—', status: 'draft', exp: T0 + 900 * D }]; if (document.getElementById('nt-u').checked) lic.push({ type: 'PPIU', no: '—', status: 'draft', exp: T0 + 900 * D }); if (document.getElementById('nt-h').checked) lic.push({ type: 'PIHK', no: '—', status: 'draft', exp: T0 + 900 * D }); TRAVELS.unshift({ id, name: n.replace(/^PT\s*/i, ''), city, prov: (CITIES.find(c => c[0] === city) || [])[1], lic, legal: 'under_review', op: 'review', payMode: document.getElementById('nt-pay').value, sub: { plan: document.getElementById('nt-plan').value, state: 'pending', renew: T0 + 30 * D, addonBranch: 0, price: ((PLANS.find(p => p.name === document.getElementById('nt-plan').value) || {}).price || 0) }, branch: { used: 0, quota: 2 }, services: ['Halal Tour'], contact: { name: '—', role: 'Owner', phone: '—', email: '—' }, npwp: '—', nib: '—', joined: nowTs(), gmv30: 0, book30: 0, rating: '—', color: colorFor(n), website: '—' }); audit('Admin Pusat', 'travel.create', 'Travel/' + id, 'success', { after: '{ "status": "draft", "subscription": "pending" }' }); closeOverlays(); toast('ok', L3(['Draft tenant dibuat', 'Tenant draft created', 'أُنشئت المسودة']), n + ' · ' + id + ' · subscription Pending', '/travel/' + id); if (location.hash.includes('?new')) history.replaceState(null, '', '#/travel'); rerender(); },
  /* approval */
  'ap-decide': el => { const a = APPROVALS.find(x => x.id === el.dataset.id); const v = el.dataset.v; confirmAction({ title: ({ approved: t('approve'), rejected: t('reject'), needs_revision: t('revise') })[v] + ' · ' + a.id, desc: esc(a.title), tone: v === 'rejected' ? 'danger' : 'primary', label: ({ approved: t('approve'), rejected: t('reject'), needs_revision: t('revise') })[v], resource: a.reqRef, reason: v !== 'approved' || a.risk >= 60, onOk: r => decideApproval(a.id, v, r) }); },
  'ap-note': el => { const ta = document.getElementById('apnote'); if (!ta.value.trim()) return ta.focus(); const a = APPROVALS.find(x => x.id === el.dataset.id); a.notes.push({ by: 'Admin Pusat', text: ta.value.trim(), ts: nowTs() }); document.getElementById('apdetail').innerHTML = apDetailHTML(a); toast('ok', L3(['Catatan disimpan', 'Note saved', 'حُفظت الملاحظة']), a.id); },
  'ap-back': () => go('/approval'),
  'doc-prev': el => modal({ title: el.dataset.n, body: `<div style="aspect-ratio:1/1.3;max-width:100%;background:var(--surface-2);border:1px solid var(--line);border-radius:8px;display:grid;place-items:center;color:var(--ink-3);text-align:center;padding:20px">${ic('filetext', 'lg')}<div><b>${esc(el.dataset.n)}</b><br>${L3(['Pratinjau dokumen via signed URL (kedaluwarsa 5 menit). Akses tercatat di audit.', 'Document preview via signed URL (expires in 5 min). Access is audited.', 'معاينة عبر رابط موقّع.'])}</div></div>`, foot: `<button class="btn" data-act="close">${t('close')}</button>` }),
  /* travel detail */
  'travel-status': el => { const x = travelById(el.dataset.id); const v = el.dataset.v; confirmAction({ title: (v === 'inactive' ? t('suspend') : t('reactivate')) + ' · ' + x.name, desc: v === 'inactive' ? L3(['Tenant tidak dapat menerima booking baru, paket di-unpublish sementara, website menampilkan status maintenance. Booking & settlement berjalan tetap diproses.', 'The tenant cannot receive new bookings, packages are temporarily unpublished, website shows maintenance. Existing bookings & settlements continue.', 'لن تستقبل الشركة حجوزات جديدة.']) : L3(['Tenant kembali aktif bila legalitas & subscription valid (divalidasi backend).', 'Tenant becomes active again if legality & subscription are valid (validated by backend).', 'تعود الشركة نشطة عند صحة الترخيص.']), tone: v === 'inactive' ? 'danger' : 'primary', resource: x.id, onOk: r => { const prev = x.op; x.op = v; audit('Admin Pusat', v === 'inactive' ? 'travel.suspend' : 'travel.reactivate', 'Travel/' + x.id, 'success', { before: '{ "status": "' + prev + '" }', after: '{ "status": "' + v + '" }', reason: r }); toast(v === 'inactive' ? 'warn' : 'ok', (v === 'inactive' ? 'Suspended · ' : 'Reactivated · ') + x.name, L3(['Tercatat di audit', 'Recorded in audit', 'مسجل']), '/travel/' + x.id + '/activity'); rerender(); } }); },
  'lic-set': el => { const x = travelById(el.dataset.id); const l = x.lic[+el.dataset.i]; const v = el.dataset.v; confirmAction({ title: (v === 'verified' ? L3(['Verifikasi ', 'Verify ', 'توثيق ']) : L3(['Tolak ', 'Reject ', 'رفض '])) + l.type, desc: esc(x.name) + ' · ' + esc(l.no), tone: v === 'verified' ? 'primary' : 'danger', reason: v !== 'verified', resource: x.id + '/' + l.type, onOk: r => { const prev = l.status; l.status = v; if (v === 'verified') l.exp = Math.max(l.exp, T0 + 3 * 365 * D); const has = s => x.lic.some(q => q.status === s); x.legal = has('rejected') ? 'rejected' : has('expired') ? 'expired' : (has('under_review') || has('submitted') || has('draft')) ? 'under_review' : has('expiring') ? 'expiring' : 'verified'; audit('Admin Pusat', 'legal.' + (v === 'verified' ? 'verify' : 'reject'), 'Travel/' + x.id + '/' + l.type, 'success', { before: '{ "status": "' + prev + '" }', after: '{ "status": "' + v + '" }', reason: r }); toast(v === 'verified' ? 'ok' : 'bad', l.type + ' → ' + L3(STATUS[v].slice(2)), x.name + ' · legal: ' + L3(STATUS[x.legal].slice(2))); rerender(); } }); },
  'sens-change': el => { toast('info', L3(['Perubahan sensitif → Approval Center', 'Sensitive change → Approval Center', 'تغيير حساس ← مركز الموافقات']), L3(['Form perubahan akan membuat request dengan before/after diff.', 'The change form creates a request with a before/after diff.', 'يُنشئ طلباً مع الفروقات.']), '/approval'); },
  'add-branch': el => { const x = travelById(el.dataset.id); const over = x.branch.used >= x.branch.quota; modal({ title: L3(['Tambah cabang', 'Add branch', 'إضافة فرع']) + ' · ' + x.name, body: `${over ? `<div class="banner warn" style="border-radius:8px;border:1px solid var(--warn-line);margin-bottom:12px">${ic('alert')}${L3(['Kuota penuh (', 'Quota full (', 'الحصة ممتلئة (']) + x.branch.used + '/' + x.branch.quota + L3([') — cabang ini akan ditagih sebagai add-on Rp 450.000/bulan dan aktif setelah invoice dibayar.', ') — this branch is billed as a Rp 450,000/month add-on and activates after payment.', ') — سيُحتسب كإضافة مدفوعة.'])}</div>` : ''}<div class="field"><label for="nb-name">${L3(['Nama cabang', 'Branch name', 'اسم الفرع'])}</label><input type="text" id="nb-name" value="Cabang ${esc(CITIES[5][0])}"></div><div class="field"><label for="nb-city">${L3(['Kota', 'City', 'المدينة'])}</label><select id="nb-city">${CITIES.map(c => `<option>${c[0]}</option>`).join('')}</select></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="add-branch-ok" data-id="${x.id}">${over ? L3(['Buat invoice add-on', 'Create add-on invoice', 'إنشاء فاتورة']) : t('save')}</button>` }); },
  'add-branch-ok': el => { const x = travelById(el.dataset.id); const over = x.branch.used >= x.branch.quota; const nm = document.getElementById('nb-name').value; if (over) { toast('info', L3(['Invoice add-on diterbitkan', 'Add-on invoice issued', 'صدرت الفاتورة']), nm + ' · ' + L3(['menunggu pembayaran', 'awaiting payment', 'بانتظار الدفع'])); } else { x.branch.used++; BRANCHES.push({ id: x.id.replace('TRV', 'BR') + '-' + x.branch.used, travel: x.id, name: nm, city: document.getElementById('nb-city').value, head: '—', status: 'active', paid: false }); toast('ok', L3(['Cabang ditambahkan', 'Branch added', 'أُضيف الفرع']), nm); } audit('Admin Pusat', 'branch.create', 'Travel/' + x.id, 'success'); closeOverlays(); rerender(); },
  'pkg-set': el => { const p = pkgById(el.dataset.id); const v = el.dataset.v; confirmAction({ title: 'Paket → ' + L3(STATUS[v].slice(2)), desc: esc(p.name) + ' · ' + esc(travelById(p.travel).name), tone: v === 'published' ? 'primary' : 'danger', reason: v !== 'published', resource: p.id, onOk: r => { const prev = p.state; p.state = v; audit('Admin Pusat', 'package.' + v, 'Package/' + p.id, 'success', { before: prev, after: v, reason: r }); toast('ok', p.name + ' → ' + L3(STATUS[v].slice(2)), L3(['Marketplace & website Travel diperbarui realtime', 'Marketplace & Travel website updated in realtime', 'تم التحديث فوراً'])); rerender(); } }); },
  /* omnichannel */
  'omni-tab': el => { OMNI.tab = el.dataset.v; document.querySelectorAll('[data-act="omni-tab"]').forEach(b => b.setAttribute('aria-selected', b === el)); OMNI.drawList(); },
  'omni-back': () => go('/omni/inbox'),
  'ctx-toggle': () => { OMNI.showCtx = !OMNI.showCtx; const o = document.getElementById('omni'); if (o) o.classList.toggle('showctx', OMNI.showCtx); },
  'cv-mode': el => { OMNI.mode = el.dataset.v; const ta = document.getElementById('cv-text'); const v = ta ? ta.value : ''; redrawConv(); const n = document.getElementById('cv-text'); if (n) { n.value = v; n.focus(); } },
  'cv-send': el => sendMsg(el.dataset.id),
  'cv-tpl': el => popAt(el, `<div class="menu" style="max-width:360px"><div class="mh">${t('template')}</div>${TEMPLATES.map((x, i) => `<button class="mi" data-act="cv-tpl-pick" data-i="${i}" style="align-items:flex-start;flex-direction:column;gap:2px"><b>${esc(x[0])}</b><span class="muted" style="font-size:12px;white-space:normal">${esc(x[1].slice(0, 90))}…</span></button>`).join('')}</div>`, 'start'),
  'cv-tpl-pick': el => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const txt = TEMPLATES[+el.dataset.i][1].replace('{nama}', c.contact.split(' ')[0]); closeOverlays(); const ta = document.getElementById('cv-text'); ta.value = txt; ta.focus(); },
  'cv-attach': () => toast('info', L3(['Lampiran', 'Attachment', 'مرفق']), L3(['File diunggah ke storage & dipindai malware sebelum dikirim.', 'Files are uploaded to storage & malware-scanned before sending.', 'يتم الفحص قبل الإرسال.'])),
  'cv-ai': () => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const ta = document.getElementById('cv-text'); ta.value = c.booking ? `Waalaikumsalam ${c.contact.split(' ')[0]}, kami sudah cek booking ${c.booking}. Status saat ini: ${L3(STATUS[bookingById(c.booking).state].slice(2))}. Kami bantu tindak lanjuti hari ini ya.` : `Waalaikumsalam, terima kasih atas minatnya. Untuk paket yang ditanyakan masih tersedia seat. Boleh kami kirimkan detail itinerary & harga?`; ta.focus(); toast('info', 'Segaloka AI', L3(['Draf saran — tinjau sebelum kirim. AI tidak mengirim atas nama Anda.', 'Suggested draft — review before sending. AI never sends on your behalf.', 'مسودة مقترحة — راجعها.'])); },
  'cv-assign': el => { const c = CONVERSATIONS.find(x => x.id === el.dataset.id); popAt(el, `<div class="menu"><div class="mh">Assign</div>${AGENTS.map(a => `<button class="mi" role="menuitemradio" aria-checked="${c.assignee === a.id}" data-act="cv-assign-pick" data-a="${a.id}"><span style="width:7px;height:7px;border-radius:50%;background:${a.online ? 'var(--ok)' : 'var(--ink-3)'}"></span>${esc(a.name)}<span class="muted" style="font-size:11.5px;margin-inline-start:auto">${a.load} open</span></button>`).join('')}<div class="sep"></div><button class="mi" data-act="cv-assign-pick" data-a="">${ic('x', 'sm')}Unassign</button></div>`); },
  'cv-assign-pick': el => { if (!can('omni.assign')) { closeOverlays(); toast('warn', t('no_perm_action'), 'omni.assign'); return; } const c = CONVERSATIONS.find(x => x.id === OMNI.active); c.assignee = el.dataset.a || null; const ag = AGENTS.find(a => a.id === c.assignee); c.messages.push({ dir: 'sys', text: ag ? 'Assigned → ' + ag.name + ' · oleh Admin Pusat' : 'Unassigned · oleh Admin Pusat', ts: nowTs() }); audit('Admin Pusat', 'conversation.assign', 'Conversation/' + c.id, 'success', { after: ag ? ag.name : 'unassigned' }); closeOverlays(); redrawConv(); OMNI.drawList(); toast('ok', ag ? 'Assigned · ' + ag.name : 'Unassigned', c.id); },
  'cv-resolve': el => { const c = CONVERSATIONS.find(x => x.id === el.dataset.id); c.status = 'resolved'; c.resolvedAt = nowTs(); c.unread = 0; c.messages.push({ dir: 'sys', text: 'Resolved · Admin Pusat', ts: nowTs() }); audit('Admin Pusat', 'conversation.resolve', 'Conversation/' + c.id, 'success'); redrawConv(); OMNI.drawList(); toast('ok', 'Resolved · ' + c.contact, L3(['Masuk ke Omnichannel Analytics', 'Counted in Omnichannel Analytics', 'يُحتسب في التحليلات'])); },
  'cv-tag': el => { const c = CONVERSATIONS.find(x => x.id === el.dataset.id); popAt(el, `<div class="menu"><div class="mh">Tag</div>${['Umrah', 'Haji', 'Refund', 'VIP', 'Komplain', 'Reschedule'].map(tg => `<button class="mi" data-act="cv-tag-pick" data-v="${tg}" role="menuitemcheckbox" aria-checked="${c.tags.includes(tg)}">${tg}</button>`).join('')}</div>`); },
  'cv-tag-pick': el => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const v = el.dataset.v; c.tags.includes(v) ? c.tags.splice(c.tags.indexOf(v), 1) : c.tags.push(v); closeOverlays(); redrawConv(); },
  'toast-demo': el => { if (el.getAttribute('aria-disabled') === 'true') return; toast('info', el.dataset.m, L3(['Simulasi — backend belum terhubung', 'Simulation — backend not connected', 'محاكاة'])); },
  /* ads */
  wizard: () => openWizard(),
  'wz-set': el => { wzCollect(); WZ[el.dataset.f] = el.dataset.v; drawWizard(); },
  'wz-toggle': el => { wzCollect(); const f = el.dataset.f; let v = el.dataset.v; if (f === 'creatives') v = +v; const arr = WZ[f]; arr.includes(v) ? arr.splice(arr.indexOf(v), 1) : arr.push(v); drawWizard(); },
  'wz-go': el => { wzCollect(); WZ.step = Math.max(0, Math.min(WZ_STEPS.length - 1, +el.dataset.v)); drawWizard(); },
  'wz-draft': () => { wzCollect(); if (!(WZ.name || '').trim()) WZ.name = 'Draft ' + fDT(nowTs()); wzCreate('draft'); },
  'wz-submit': () => { wzCollect(); if (!(WZ.name || '').trim()) { WZ.step = 0; drawWizard(); toast('warn', L3(['Nama campaign wajib diisi', 'Campaign name is required', 'الاسم مطلوب']), ''); return; } wzCreate('review'); },
  'camp-set': el => { const c = campById(el.dataset.id); const v = el.dataset.v; const destructive = ['paused', 'completed', 'archived', 'draft'].includes(v); confirmAction({ title: 'Campaign → ' + L3(STATUS[v].slice(2)), desc: esc(c.name), tone: destructive ? 'danger' : 'primary', reason: destructive, resource: c.id, onOk: r => { const prev = c.state; c.state = v;  const ap = APPROVALS.find(a => a.reqRef === c.id && ['waiting', 'in_progress'].includes(a.status)); if (ap && prev === 'review') { ap.status = v === 'scheduled' ? 'approved' : 'rejected'; ap.history.push({ t: 'Diputuskan dari Campaign Detail', ts: nowTs(), tone: v === 'scheduled' ? 'ok' : 'bad' }); } audit('Admin Pusat', 'campaign.status', 'Campaign/' + c.id, 'success', { before: prev, after: v, reason: r }); toast('ok', c.name + ' → ' + L3(STATUS[v].slice(2)), L3(['Status tersinkron ke ad server Segaloka & Analytics', 'Status synced to the Segaloka ad server & Analytics', 'تمت المزامنة'])); rerender(); } }); },
  /* finance */
  'run-recon': () => confirmAction({ title: L3(['Jalankan rekonsiliasi', 'Run reconciliation', 'تشغيل المطابقة']), desc: L3(['Mencocokkan mutasi bank, ledger, dan data gateway untuk 24 jam terakhir. Proses berjalan di background.', 'Matches bank statements, ledger and gateway data for the last 24h. Runs in the background.', 'مطابقة آخر 24 ساعة.']), reason: false, resource: 'REC-260924', onOk: () => { let k = 0; PAYMENTS.forEach(p => { if (p.status === 'paid' && p.recon === 'pending') { p.recon = 'reconciled'; k++; } }); audit('Admin Pusat', 'reconciliation.run', 'Batch/REC-260924', 'success', { after: '{ "matched": ' + k + ' }' }); toast('ok', L3(['Rekonsiliasi selesai', 'Reconciliation complete', 'اكتملت المطابقة']), k + ' matched · ' + PAYMENTS.filter(p => p.recon === 'unmatched' || p.recon === 'mismatch').length + ' ' + L3(['perlu review manual', 'need manual review', 'تحتاج مراجعة']), '/finance/reconciliation'); rerender(); } }),
  'wd-approve': el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); confirmAction({ title: 'Approve withdrawal · ' + w.id, desc: esc(w.party) + ' (' + w.partyType + ') · <b>' + money(w.amount, true) + '</b><br>' + esc(w.basis), resource: w.id, reason: w.amount > 50e6, onOk: r => { w.state = 'approved'; audit('Admin Pusat', 'withdrawal.approve', 'Withdrawal/' + w.id, 'success', { before: 'pending', after: 'approved', reason: r }); toast('ok', 'Withdrawal approved · ' + w.id, L3(['Disbursement dijadwalkan oleh payout worker', 'Disbursement scheduled by payout worker', 'تمت جدولة الصرف'])); rerender(); } }); },
  'audit-diff': el => { const a = AUDIT.find(x => x.id === el.dataset.id); drawer({ title: a.action, sub: `<span class="mono">${esc(a.id)}</span>`, body: `<dl class="dl"><dt>Actor</dt><dd>${esc(a.actor)}</dd><dt>Resource</dt><dd class="mono">${esc(a.resource)}</dd><dt>Timestamp</dt><dd>${esc(fDT(a.ts))}</dd><dt>Source</dt><dd>${esc(a.source)}</dd><dt>Result</dt><dd>${esc(a.result)}</dd>${a.reason ? `<dt>${t('reason')}</dt><dd>${esc(a.reason)}</dd>` : ''}</dl><div style="margin-top:14px;border:1px solid var(--line);border-radius:8px;overflow:hidden"><div class="diffrow diffhead" style="grid-template-columns:1fr 1fr"><div>Before</div><div>After</div></div><div class="diffrow" style="grid-template-columns:1fr 1fr"><div class="b mono" style="text-decoration:none">${esc(a.before || '—')}</div><div class="a mono">${esc(a.after || '—')}</div></div></div>` }); },
  'brand-save': el => { if (el.getAttribute('aria-disabled') === 'true') return; const g = i => document.getElementById(i).value; const before = JSON.stringify({ name: BRAND.name, color: BRAND.color }); BRAND.name = g('br-name') || BRAND.name; BRAND.mark = g('br-mark') || BRAND.mark; BRAND.color = g('br-color'); BRAND.legal = g('br-legal'); audit('Admin Pusat', 'brand.update', 'Config/brand', 'success', { before, after: JSON.stringify({ name: BRAND.name, color: BRAND.color }) }); APP.renderSide(); toast('ok', L3(['Brand diperbarui', 'Brand updated', 'تم تحديث الهوية']), L3(['Shell membaca konfigurasi baru tanpa reload', 'Shell picked up the new config without reload', 'دون إعادة تحميل'])); }
});


/* Control Center database maintenance action */
/* pembersihan data demo hanya atas konfirmasi pemilik (tidak otomatis) */
A['sb-purge'] = () => confirmAction({ title: L3(['Cadangkan & hapus data demo', 'Back up & remove demo data', 'نسخ وحذف البيانات التجريبية']), desc: L3(['Semua Travel, booking, pembayaran, dan entitas demo lain disalin ke tabel control_center.demo_backup lalu dihapus. Konfigurasi (fee, plan, slot iklan, template) tetap. Setelah ini semua angka dihitung dari data nyata.', 'All demo Travels, bookings, payments and other entities are copied to control_center.demo_backup and then removed. Configuration (fees, plans, ad slots, templates) is kept. Afterwards every figure is computed from real data.', 'سيتم النسخ ثم الحذف.']), tone: 'danger', reason: true, label: L3(['Cadangkan & hapus', 'Back up & remove', 'نسخ وحذف']), resource: 'Supabase/' + SB.project, onOk: async () => { SB.purgeOk = true; try { await sbProductionize(); ENTITY_ARRAYS().forEach(a => { a.length = 0; }); SB.saved = {}; await sbLoad(); clearFakeStats(); SB.needPurge = false; audit('Admin Pusat', 'database.production', 'Supabase/' + SB.project + '/control_center', 'success', { source: 'Control Center', after: 'demo data -> demo_backup' }); await sbFlush(); rtEmit(1); toast('ok', L3(['Mode produksi aktif', 'Production mode on', 'وضع الإنتاج']), L3(['Data demo dipindah ke cadangan', 'Demo data moved to backup', 'نُقلت'])); APP.renderBanners(); rerender(); } catch (e) { toast('bad', L3(['Gagal', 'Failed', 'فشل']), String(e.message || e)); } } });


/* Control Center-only demo realtime simulator */
function controlCenterRealtime() {
  if (!DEMO || !CONVERSATIONS.length || !TRAVELS.length || S.ux === 'offline' || document.hidden || (typeof SB !== 'undefined' && SB.on)) return; rtTick++;
  const kind = ['approval', 'payment', 'message', 'payment', 'message'][rtTick % 5];
  if (kind === 'approval') { const tr = pick(TRAVELS); const a = { id: 'APR-' + (19900 + rtTick), type: 'legal_doc', domain: 'Legalitas', title: 'Dokumen BPW diperbarui — ' + tr.name, requester: tr.name, reqRef: tr.id, reqRoute: '/travel/' + tr.id + '/legal', status: 'waiting', priority: 'p2', assignee: null, ts: nowTs(), risk: ri(10, 40), docs: [['PDF', 'Sertifikat BPW.pdf', '700 KB']], ctx: [['Travel ID', tr.id], ['Izin', 'BPW']], notes: [], history: [{ t: 'Request diajukan oleh ' + tr.name, ts: nowTs(), tone: 'info' }], fresh: true }; APPROVALS.unshift(a); NOTIFS.unshift({ cat: 'approval', tone: 'info', title: L3(['Approval baru masuk', 'New approval request', 'طلب موافقة جديد']), sub: a.title, route: '/approval/' + a.id, ts: nowTs(), unread: true }); toast('info', L3(['Approval baru masuk', 'New approval request', 'طلب موافقة جديد']), a.title, '/approval/' + a.id); if (S.route.startsWith('/approval') && window.APV) APV.refreshList(); }
  if (kind === 'payment') { const p = PAYMENTS.find(x => x.status === 'pending'); if (!p) return; p.status = 'paid'; p.recon = 'pending'; p.fresh = nowTs(); const b = bookingById(p.booking); if (b && b.state === 'awaiting_payment') b.state = 'partially_paid'; NOTIFS.unshift({ cat: 'payment', tone: 'ok', title: L3(['Pembayaran dikonfirmasi', 'Payment confirmed', 'تم تأكيد الدفع']), sub: p.id + ' · ' + money(p.amount), route: '/finance/payment/' + p.id, ts: nowTs(), unread: true }); toast('ok', L3(['Pembayaran dikonfirmasi (webhook)', 'Payment confirmed (webhook)', 'تم تأكيد الدفع']), p.id + ' · ' + money(p.amount) + ' · ' + p.provider, '/finance/payment/' + p.id); audit('System', 'webhook.payment.paid', 'Payment/' + p.id, 'success', { source: 'Worker · webhook-consumer' }); if (S.route === '/finance' || S.route === '/finance/transactions') { if (TBL.fintx) refreshTable('fintx'); if (TBL.tx) refreshTable('tx'); const row = document.querySelector(`tr[data-row="${p.id}"]`); if (row) row.classList.add('flash'); const u = document.getElementById('fin-upd'); if (u) u.textContent = t('updated') + ' ' + t('just_now'); } }
  if (kind === 'message') { const c = CONVERSATIONS.find(x => x.status !== 'closed' && x.status !== 'resolved' && x.id !== (window.OMNI && OMNI.active)) || CONVERSATIONS[0]; const texts = ['Kak, mohon info lanjutannya ya 🙏', 'Apakah bisa dibantu hari ini?', 'Baik, saya tunggu kabarnya.', 'Untuk pembayaran pelunasan bisa via QRIS?']; c.messages.push({ dir: 'in', text: pick(texts), ts: nowTs() }); c.ts = nowTs(); c.unread++; if (c.status === 'pending') c.status = 'open'; if (window.OMNI && S.route.startsWith('/omni/inbox')) OMNI.onIncoming(c); else toast('info', L3(['Pesan baru', 'New message', 'رسالة جديدة']) + ' · ' + c.contact, c.messages[c.messages.length - 1].text, '/omni/inbox/' + c.id); }
  APP.renderTop(); updateSideBadges();
}


/* ======================= CONTROL CENTER SEARCH ======================= */
const CONTROL_CENTER_SEARCH_SCOPES = [['all', 'f_all'], ['travel', 'Travel'], ['vendor', 'Vendor'], ['affiliate', 'Affiliate'], ['traveler', 'Traveler'], ['booking', 'Booking'], ['tx', 'Transaksi'], ['package', 'Paket'], ['campaign', 'Campaign'], ['page', 'Menu']];
function controlCenterSearchIndex() {
  return [
    ...TRAVELS.map(x => ({ type: 'travel', icon: 'building', title: x.name, sub: x.id + ' · ' + x.city, r: '/travel/' + x.id, s: x.name + ' ' + x.id + ' ' + x.city })),
    ...VENDORS.map(x => ({ type: 'vendor', icon: 'store', title: x.name, sub: x.id + ' · ' + x.cats.join(', '), r: '/vendor/' + x.id, s: x.name + ' ' + x.id + ' ' + x.cats.join(' ') })),
    ...AFFILIATES.map(x => ({ type: 'affiliate', icon: 'link', title: x.name, sub: x.id + ' · kode ' + x.code, r: '/affiliate', s: x.name + ' ' + x.id + ' ' + x.code })),
    ...TRAVELERS.map(x => ({ type: 'traveler', icon: 'user', title: x.name, sub: x.id + ' · ' + x.city, r: '/traveler', s: x.name + ' ' + x.id + ' ' + x.phone })),
    ...BOOKINGS.map(x => ({ type: 'booking', icon: 'calendar', title: x.id, sub: (TRAVELERS.find(v => v.id === x.traveler) || {}).name + ' · ' + (PACKAGES.find(p => p.id === x.pkg) || {}).name, r: '/booking/' + x.id, s: x.id + ' ' + (TRAVELERS.find(v => v.id === x.traveler) || {}).name })),
    ...PAYMENTS.map(x => ({ type: 'tx', icon: 'repeat', title: x.id, sub: money(x.amount) + ' · ' + x.provider + ' · ' + x.ref, r: '/finance/payment/' + x.id, s: x.id + ' ' + x.ref + ' ' + x.booking })),
    ...PACKAGES.map(x => ({ type: 'package', icon: 'package', title: x.name, sub: x.id + ' · ' + travelById(x.travel).name, r: '/marketplace/packages', s: x.name + ' ' + x.id + ' ' + travelById(x.travel).name })),
    ...CAMPAIGNS.map(x => ({ type: 'campaign', icon: 'target', title: x.name, sub: x.id + ' · ' + L3(STATUS[x.state].slice(2)), r: '/ads/campaign/' + x.id, s: x.name + ' ' + x.id })),
    ...Object.values(NAVIDX).filter(n => n.r && can(n.p)).map(n => ({ type: 'page', icon: n.i, title: t(n.id), sub: navTrail(n.id).map(x => x[0]).join(' › '), r: n.r, s: t(n.id) + ' ' + t(n.g) }))
  ];
}
APP.searchScopes = () => CONTROL_CENTER_SEARCH_SCOPES;
APP.searchIndex = () => controlCenterSearchIndex();
APP.searchRecent = () => ['/approval', '/omni/inbox', '/finance'];


/* ======================= CONTROL CENTER WITHDRAWAL ======================= */
function wdAdminActs(w) { const b = (a, cls, label) => permBtn('finance.withdrawal', label, `data-act="wd-do" data-a="${a}" data-id="${w.id}" data-mut`, 'sm ' + cls);
  return ({ pending: [b('approve', 'primary', t('approve')), b('revise', '', L3(['Kembalikan', 'Return', 'إرجاع'])), b('hold', '', L3(['Tahan', 'Hold', 'تعليق'])), b('reject', 'badb', t('reject'))], hold: [b('release', 'primary', L3(['Lepas tahan', 'Release', 'إلغاء التعليق'])), b('reject', 'badb', t('reject'))], approved: [b('pay', 'primary', L3(['Tandai ditransfer', 'Mark transferred', 'تم التحويل'])), b('unapprove', '', L3(['Batalkan persetujuan', 'Revoke approval', 'إلغاء الموافقة']))] })[w.state] || []; }
/* admin: daftar + detail */
reroute('/finance/withdrawal', () => dirPage({ nav: 'fin_wd', desc: L3(['Penarikan saldo Vendor, Travel (VIA_SEGALOKA), dan Affiliate. Finance dapat menyetujui, mengembalikan untuk revisi, menahan, menolak, lalu menandai sudah ditransfer dengan bukti. Pihak terkait diberi tahu di setiap langkah.', 'Balance withdrawals for Vendors, Travels (VIA_SEGALOKA) and Affiliates. Finance can approve, return for revision, hold, reject, then mark as transferred with proof. The party is notified at each step.', 'السحوبات.']), tableId: 'wd', cfg: { name: 'Withdrawal', search: r => r.id + r.party, rows: () => WITHDRAWALS, route: r => '/finance/withdrawal/' + r.id, filters: [{ v: 'all', label: t('f_all'), fn: () => true }, { v: 'todo', label: L3(['Perlu tindakan', 'Needs action', 'بحاجة لإجراء']), fn: r => ['pending', 'hold', 'approved'].includes(r.state) }, ...['Vendor', 'Travel', 'Affiliate'].map(s => ({ v: s, label: s, fn: r => r.partyType === s })), { v: 'needs_revision', label: L3(['Dikembalikan', 'Returned', 'مُرجع']), fn: r => r.state === 'needs_revision' }], cols: [{ k: 'id', label: 'ID', render: r => `<a class="mono" href="#/finance/withdrawal/${r.id}"><b>${r.id}</b></a><div class="muted" style="font-size:11.5px">${rel(r.ts)}${r.resubmits ? ' · ' + L3(['kirim ulang ', 'resubmitted ', 'أُعيد ']) + r.resubmits + '×' : ''}</div>` }, { k: 'party', label: L3(['Penerima', 'Recipient', 'المستفيد']), render: r => `${esc(r.party)} <span class="chip" style="height:18px">${r.partyType}</span>` }, { k: 'basis', label: 'Basis' }, { k: 'amount', label: 'Amount', cls: 'r tnum', render: r => money(r.amount, true) }, { k: 'state', label: t('status'), render: r => st(r.state) }, { k: 'act', label: t('action'), cls: 'r', sort: false, render: r => { const L = wdAdminActs(r); return L.length ? `<div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${L.slice(0, 2).join('')}${L.length > 2 ? `<a class="btn sm ghost" href="#/finance/withdrawal/${r.id}">${ic('more', 'sm')}</a>` : ''}</div>` : '—'; } }] } }));
route('/finance/withdrawal/:id', p => { const w = WITHDRAWALS.find(x => x.id === p.id); if (!w) return { html: `<div class="page">${stateBlock('empty')}</div>` };
  return { html: `<div class="page">${phead({ crumbs: [[t('g_fin'), '/finance'], ['Withdrawal', '/finance/withdrawal'], [w.id, '']], title: 'Withdrawal ' + w.id, desc: esc(w.party) + ' · ' + money(w.amount, true), actions: wdAdminActs(w).join('') })}${wdDetail(w, 'admin')}</div>` }; });
A['wd-approve'] = el => { el.dataset.a = 'approve'; A['wd-do'](el); };
A['wd-do'] = el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); if (!w) return; const a = el.dataset.a; const ws = wdWs(w);
  const cfg = { approve: [t('approve'), 'primary', 'approved', w.amount > 50e6], revise: [L3(['Kembalikan untuk revisi', 'Return for revision', 'إرجاع للمراجعة']), '', 'needs_revision', true], hold: [L3(['Tahan', 'Hold', 'تعليق']), '', 'hold', true], reject: [t('reject'), 'danger', 'rejected', true], release: [L3(['Lepas tahan', 'Release', 'إلغاء التعليق']), 'primary', 'pending', false], unapprove: [L3(['Batalkan persetujuan', 'Revoke approval', 'إلغاء الموافقة']), '', 'pending', true] }[a];
  if (a === 'pay') { modal({ title: L3(['Tandai sudah ditransfer · ', 'Mark as transferred · ', 'تم التحويل · ']) + w.id, body: `<p class="muted" style="margin-top:0">${esc(w.party)} · <b>${money(w.amount, true)}</b>${w.bank ? ' → ' + esc(w.bank.name + ' ' + w.bank.no) : ''}</p>` + fields([{ k: 'ref', label: L3(['No. referensi transfer', 'Transfer reference', 'مرجع التحويل']), req: true }], 'wp-') + `<div class="field"><label for="wp-file">${L3(['Bukti transfer (opsional)', 'Transfer proof (optional)', 'إثبات التحويل'])}</label><input type="file" id="wp-file" accept="image/*,.pdf"></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="wd-pay-go" data-id="${w.id}">${L3(['Simpan', 'Save', 'حفظ'])}</button>` }); return; }
  if (!cfg) return;
  confirmAction({ title: cfg[0] + ' · ' + w.id, desc: esc(w.party) + ' (' + w.partyType + ') · <b>' + money(w.amount, true) + '</b>' + (a === 'revise' ? '<br>' + L3(['Pihak terkait bisa memperbaiki lalu mengirim ulang.', 'The party can fix it and resubmit.', 'يمكن التعديل.']) : a === 'reject' ? '<br>' + L3(['Saldo dikembalikan ke pihak terkait.', 'The balance is returned to the party.', 'يعاد الرصيد.']) : ''), tone: cfg[1] || 'primary', label: cfg[0], reason: cfg[3], resource: 'Withdrawal/' + w.id, onOk: r => { const prev = w.state; w.state = cfg[2]; w.updated = nowTs(); wdHist(w, cfg[2], 'Finance · Admin Pusat', r); if (cfg[2] === 'rejected') wdRefund(w); wdSyncApproval(w, cfg[2], r);
    audit('Admin Pusat', 'withdrawal.' + a, 'Withdrawal/' + w.id, 'success', { before: prev, after: cfg[2], reason: r }); toast('ok', 'Withdrawal ' + w.id + ' → ' + stLbl(cfg[2]), esc(w.party)); rerender(); } }); };
A['wd-pay-go'] = async el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); const v = formVals([{ k: 'ref', req: true }], 'wp-'); if (!v) return; const f = (document.getElementById('wp-file') || {}).files; const file = f && f[0];
  try { if (file) await saveUpload(file, { ref: w.id, kind: 'wdproof', by: 'Finance · Admin Pusat', byWs: 'admin', state: 'verified' }); } catch (e) { toast('bad', 'Upload', String(e.message || e)); return; }
  const prev = w.state; w.state = 'disbursed'; w.transferRef = v.ref; w.disbursedAt = nowTs(); wdHist(w, 'disbursed', 'Finance · Admin Pusat', '', { ref: v.ref }); wdSyncApproval(w, 'disbursed');
  audit('Admin Pusat', 'withdrawal.disburse', 'Withdrawal/' + w.id, 'success', { before: prev, after: 'disbursed', reason: 'Ref ' + v.ref }); closeOverlays(); toast('ok', L3(['Ditandai sudah ditransfer', 'Marked as transferred', 'تم التحويل']), w.id + ' · ' + v.ref); rerender(); };

/* approval center → withdrawal memakai id yang tepat */
const _decideApproval = decideApproval;
decideApproval = function (id, v, reason) { const a = APPROVALS.find(x => x.id === id); if (a && a.type === 'withdrawal') { const w = WITHDRAWALS.find(x => x.id === a.wd) || WITHDRAWALS.find(x => x.party === a.requester && x.state === 'pending'); if (w && ['pending', 'hold'].includes(w.state)) { const to = v === 'approved' ? 'approved' : v === 'rejected' ? 'rejected' : v === 'needs_revision' ? 'needs_revision' : 'hold'; const prev = w.state; w.state = to; wdHist(w, to, 'Finance · Approval Center', reason); if (to === 'rejected') wdRefund(w); audit('Admin Pusat', 'withdrawal.' + to, 'Withdrawal/' + w.id, 'success', { before: prev, after: to, reason }); a.wd = w.id; a.type = 'withdrawal_done'; const r = _decideApproval(id, v, reason); a.type = 'withdrawal'; return r; } } return _decideApproval(id, v, reason); };


/* ======================= CONTROL CENTER MODERATION ACTIONS ======================= */
Object.assign(A, {
  'rv-mod': el => { const r = REVIEWS.find(x => x.id === el.dataset.id); if (!r) return; const hide = r.state !== 'hidden'; confirmAction({ title: (hide ? L3(['Sembunyikan ulasan', 'Hide review', 'إخفاء']) : L3(['Tampilkan lagi', 'Show again', 'إظهار'])) + ' · ' + r.id, desc: esc(r.text.slice(0, 160)), tone: hide ? 'danger' : 'primary', reason: hide, resource: 'Review/' + r.id, onOk: reason => { r.state = hide ? 'hidden' : 'published'; r.hideReason = hide ? reason : ''; recompute(); audit('Admin Pusat', hide ? 'review.hide' : 'review.show', 'Review/' + r.id, 'success', { reason }); if (hide) partyNotify([ntKey('traveler', r.traveler), ntKey('travel', r.travel)], 'marketplace', 'warn', L3(['Ulasan disembunyikan admin', 'Review hidden by admin', 'أُخفي التقييم']), reason, { traveler: '/p/traveler/bookings/' + r.booking, travel: '/p/travel/reviews' }); toast('ok', stLbl(hide ? 'inactive' : 'active'), r.id); rerender(); } }); },
  'sd-adm-withdraw': el => { const o = SD_OFF.find(x => x.id === el.dataset.id); if (!o || o.state !== 'sent') return; confirmAction({ title: L3(['Tarik penawaran (moderasi)', 'Withdraw offer (moderation)', 'سحب العرض']) + ' · ' + o.id, desc: esc(travelById(o.travel).name) + ' · ' + money(o.price, true) + '/pax', tone: 'danger', label: L3(['Tarik', 'Withdraw', 'سحب']), resource: 'SegaDealsOffer/' + o.id, onOk: reason => { o.state = 'withdrawn'; sdSweep(); audit('Admin Pusat', 'segadeals.offer.moderate_withdraw', 'SegaDealsOffer/' + o.id, 'success', { before: 'sent', after: 'withdrawn', reason }); toast('ok', L3(['Penawaran ditarik', 'Offer withdrawn', 'سُحب العرض']), o.id); closeOverlays(); rerender(); } }); }
});


/* ======================= CONTROL CENTER SEGADEALS ADMIN ACTIONS ======================= */
Object.assign(A, {

  'sd-cfg': () => modal({ title: L3(['Pengaturan SegaDeals', 'SegaDeals settings', 'الإعدادات']), body: fields([{ k: 'fee', label: L3(['Biaya default per pax (Rp)', 'Default fee per pax (Rp)', 'الرسوم']), type: 'number', req: true, min: 0, step: 10000, def: SDCFG.fee }, { k: 'maxFee', label: L3(['Batas maksimum per pax (Rp)', 'Maximum per pax (Rp)', 'الحد الأقصى']), type: 'number', req: true, min: 0, step: 10000, def: SDCFG.maxFee }, { k: 'terms', label: L3(['S&K (satu poin per baris)', 'T&C (one point per line)', 'الشروط']), type: 'textarea', req: true, def: SDCFG.terms.join('\n') }, { k: 'bump', label: L3(['Wajibkan semua Travel menyetujui ulang', 'Require all Travels to re-accept', 'إعادة الموافقة']), type: 'toggle' }], 'sc-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="sd-cfg-go">${t('save')}</button>` }),
  'sd-cfg-go': () => { const v = formVals([{ k: 'fee', type: 'number', req: true }, { k: 'maxFee', type: 'number', req: true }, { k: 'terms', req: true }, { k: 'bump', type: 'toggle' }], 'sc-'); if (!v) return; if (v.fee > v.maxFee) { toast('bad', L3(['Biaya melebihi batas maksimum', 'Fee exceeds maximum', 'يتجاوز']), ''); return; } const before = money(SDCFG.fee) + '/v' + SDCFG.version; Object.assign(SDCFG, { fee: v.fee, maxFee: v.maxFee, terms: v.terms.split('\n').map(x => x.trim()).filter(Boolean) }); if (v.bump) SDCFG.version++; audit('Admin Pusat', 'segadeals.config.update', 'Settings/segadeals', 'success', { before, after: money(SDCFG.fee) + '/v' + SDCFG.version }); if (v.bump) partyNotify(TRAVELS.filter(x => x.sdTerms).map(x => ntKey('travel', x.id)), 'marketplace', 'warn', L3(['S&K SegaDeals diperbarui — setujui ulang', 'SegaDeals T&C updated — please re-accept', 'حُدثت الشروط']), '', { travel: '/p/travel/segadeals' }); closeOverlays(); toast('ok', L3(['Pengaturan disimpan', 'Settings saved', 'حُفظ']), ''); rerender(); },
  'sd-trfee': el => { const tr = travelById(el.dataset.id); modal({ title: L3(['Biaya SegaDeals · ', 'SegaDeals fee · ', 'الرسوم · ']) + tr.name, body: fields([{ k: 'fee', label: L3(['Biaya per pax (Rp) — kosongkan untuk default', 'Fee per pax (Rp) — blank for default', 'الرسوم']), type: 'number', min: 0, max: SDCFG.maxFee, step: 10000, def: tr.sdFee != null ? tr.sdFee : '' }], 'tf-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="sd-trfee-go" data-id="${tr.id}">${t('save')}</button>` }); },
  'sd-trfee-go': el => { const tr = travelById(el.dataset.id); const v = formVals([{ k: 'fee', type: 'number' }], 'tf-'); if (!v) return; if (v.fee !== '' && (v.fee < 0 || v.fee > SDCFG.maxFee)) { toast('bad', L3(['Di luar batas', 'Out of range', 'خارج الحد']), money(SDCFG.maxFee)); return; } const prev = sdFeeFor(tr); tr.sdFee = v.fee === '' ? null : v.fee; audit('Admin Pusat', 'segadeals.fee.override', 'Travel/' + tr.id, 'success', { before: money(prev), after: money(sdFeeFor(tr)) }); partyNotify([ntKey('travel', tr.id)], 'marketplace', 'info', L3(['Biaya SegaDeals Anda: ', 'Your SegaDeals fee: ', 'رسومك: ']) + money(sdFeeFor(tr)) + '/pax', '', { travel: '/p/travel/segadeals' }); closeOverlays(); rerender(); },
  'sd-revoke': el => { const tr = travelById(el.dataset.id); const on = !(tr.sdTerms && tr.sdTerms.revoked); confirmAction({ title: (on ? L3(['Cabut akses SegaDeals · ', 'Revoke SegaDeals · ', 'إلغاء · ']) : L3(['Pulihkan akses SegaDeals · ', 'Restore SegaDeals · ', 'استعادة · '])) + tr.name, tone: on ? 'danger' : 'primary', reason: on, resource: 'Travel/' + tr.id, onOk: r => { tr.sdTerms = Object.assign({}, tr.sdTerms, { revoked: on, reason: on ? r : '' }); audit('Admin Pusat', on ? 'segadeals.revoke' : 'segadeals.restore', 'Travel/' + tr.id, 'success', { reason: r }); partyNotify([ntKey('travel', tr.id)], 'marketplace', on ? 'bad' : 'ok', on ? L3(['Akses SegaDeals dicabut', 'SegaDeals access revoked', 'أُلغي']) : L3(['Akses SegaDeals dipulihkan', 'SegaDeals access restored', 'استعيد']), r || '', { travel: '/p/travel/segadeals' }); rerender(); } }); }
});


/* ======================= CONTROL CENTER PAYMENT GATEWAY ======================= */
/* ---------- Admin: pengaturan gateway ---------- */
const GW_SECRETS = { midtrans: [['midtrans_server_key', 'Midtrans Server Key']], xendit: [['xendit_secret_key', 'Xendit Secret API Key'], ['xendit_callback_token', 'Xendit Callback Verification Token']] };
const GW_RT = { at: 0, sec: {}, rows: [] };
async function gwLoad() { if (typeof SB === 'undefined' || !SB.on) return; GW_RT.at = Date.now(); try { const s = await sql('select * from control_center.sg_pay_secret_status()'); GW_RT.sec = Object.fromEntries(s.map(x => [x.name, x.updated_at])); GW_RT.live = true; } catch (e) { GW_RT.live = false; } try { GW_RT.rows = await sql(`select id, target_kind, target_id, amount, provider, status, error, (extract(epoch from updated_at)*1000)::bigint as t from control_center.pay_outbox order by created_at desc limit 12`); } catch (e) { GW_RT.rows = []; } if (/^\/system\/payment/.test(S.route)) rerender(); }
function gwPanel() { if (Date.now() - GW_RT.at > 8000) setTimeout(gwLoad, 0); const sec = GW_SECRETS[PAYGW.provider] || [];
  return `<section class="panel" style="margin-bottom:14px;border-color:var(--accent)"><div class="panel-h"><h3>${ic('card', 'sm')}${L3(['Gateway pembayaran otomatis', 'Automatic payment gateway', 'بوابة الدفع'])}</h3>${GW_RT.live ? st('active') : st('pending')}</div><div class="panel-b">
  <p class="muted" style="margin-top:0">${L3(['Pembayaran masuk (DP & pelunasan jamaah, deposit SegaDeals) dibuat di gateway dan terkonfirmasi otomatis lewat webhook. Refund & withdrawal tetap dikonfirmasi manual.', 'Incoming payments (pilgrim deposits & balances, SegaDeals deposits) are created at the gateway and confirmed automatically via webhook. Refunds & withdrawals remain manually confirmed.', 'تأكيد تلقائي.'])}</p>
  <div class="grid g2" style="gap:10px"><div class="field"><label for="gw-provider">Provider</label><select id="gw-provider">${[['midtrans', 'Midtrans (Snap)'], ['xendit', 'Xendit (Invoice)']].map(o => `<option value="${o[0]}" ${PAYGW.provider === o[0] ? 'selected' : ''}>${o[1]}</option>`).join('')}</select></div><div class="field"><label for="gw-mode">Mode</label><select id="gw-mode">${[['sandbox', 'Sandbox'], ['production', 'Production']].map(o => `<option value="${o[0]}" ${PAYGW.mode === o[0] ? 'selected' : ''}>${o[1]}</option>`).join('')}</select></div></div>
  <button class="btn sm" data-act="gw-save">${t('save')}</button>
  <div class="eyebrow" style="margin:14px 0 6px">${L3(['Kunci (disimpan di Vault, tidak pernah ditampilkan)', 'Keys (stored in Vault, never shown)', 'المفاتيح'])}</div>
  ${sec.map(([k, l]) => `<div class="docrow"><span class="fi">${ic('lock', 'sm')}</span><span class="body"><b>${esc(l)}</b><span>${GW_RT.sec[k] ? L3(['Tersimpan ', 'Stored ', 'محفوظ ']) + rel(new Date(GW_RT.sec[k]).getTime()) : L3(['Belum diisi', 'Not set', 'غير مضبوط'])}</span></span><input type="password" id="gws-${k}" placeholder="••••" style="max-width:220px;border:1px solid var(--line-strong);border-radius:6px;padding:4px 6px;background:var(--surface)"><button class="btn sm primary" data-act="gw-sec" data-k="${k}">${t('save')}</button></div>`).join('')}
  <div class="eyebrow" style="margin:14px 0 6px">Webhook URL</div>
  <div class="docrow"><span class="fi">URL</span><span class="body"><b class="mono" style="font-size:12px;word-break:break-all">${PAY_FN}/webhook/${PAYGW.provider}</b><span>${PAYGW.provider === 'xendit' ? L3(['Xendit Dashboard › Settings › Webhooks › Invoices paid', 'Xendit Dashboard › Settings › Webhooks › Invoices paid', '']) : L3(['Midtrans Dashboard › Settings › Payment › Notification URL', 'Midtrans Dashboard › Settings › Payment › Notification URL', ''])}</span></span><button class="btn sm ghost" data-act="copy" data-v="${PAY_FN}/webhook/${PAYGW.provider}">${ic('copy', 'sm')}</button></div>
  <div class="eyebrow" style="margin:14px 0 6px">${L3(['Transaksi gateway terbaru', 'Latest gateway transactions', 'أحدث المعاملات'])}</div>
  ${GW_RT.rows.length ? tbl(['ID', L3(['Untuk', 'For', 'لـ']), 'Rp', 'Provider', t('status'), ''], GW_RT.rows.map(x => `<tr><td class="mono">${esc(x.id)}</td><td class="mono">${esc(x.target_id)}</td><td class="r tnum">${money(+x.amount)}</td><td>${esc(x.provider || '—')}</td><td>${st(x.status === 'created' ? 'pending' : x.status === 'queued' ? 'pending' : x.status)}${x.error ? `<div class="muted" style="font-size:11px">${esc(x.error)}</div>` : ''}</td><td>${rel(+x.t)}</td></tr>`)) : `<span class="muted">—</span>`}</div></section>`; }
Object.assign(A, {
  'gw-save': () => { const prev = JSON.stringify(PAYGW); PAYGW.provider = document.getElementById('gw-provider').value; PAYGW.mode = document.getElementById('gw-mode').value; audit('Admin Pusat', 'payment.gateway.update', 'Settings/pay_gateway', 'success', { before: prev, after: JSON.stringify(PAYGW) }); toast('ok', L3(['Gateway disimpan', 'Gateway saved', 'حُفظ']), PAYGW.provider + ' · ' + PAYGW.mode); rerender(); },
  'gw-sec': async el => { const k = el.dataset.k; const v = (document.getElementById('gws-' + k) || {}).value || ''; if (!v.trim()) return; try { await sql(`select control_center.sg_pay_set_secret('${k}', ${dq(v.trim())})`); audit('Admin Pusat', 'payment.gateway.secret.set', 'Vault/pay_' + k, 'success'); toast('ok', L3(['Kunci disimpan di Vault', 'Key stored in Vault', 'حُفظ']), k); await gwLoad(); } catch (e) { toast('bad', L3(['Gagal menyimpan kunci', 'Failed to store key', 'فشل']), sbErrText(e)); } }
});
(() => { const R = ROUTES.find(x => x.pattern === '/system/payment'); if (!R) return; const prev = R.fn; reroute('/system/payment', p => { const out = prev(p); if (!out || !out.html) return out; const k = out.html.indexOf('<div class="grid'); out.html = k > 0 ? out.html.slice(0, k) + gwPanel() + out.html.slice(k) : out.html; return out; }); })();
/* admin SegaDeals: setoran menunggu dibayar (tanpa tombol konfirmasi manual) */
(() => { const R = ROUTES.find(x => x.pattern === '/marketplace/segadeals'); if (!R) return; const prev = R.fn; reroute('/marketplace/segadeals', p => { const out = prev(p); if (out && out.html) out.html = out.html.replace(/<button class="btn sm primary"[^>]*data-act="sd-dep-ok"[^>]*>.*?<\/button>|<button class="btn sm badb"[^>]*data-act="sd-dep-no"[^>]*>.*?<\/button>/g, '').replace(L3(['Setoran deposit menunggu konfirmasi', 'Top-ups awaiting confirmation', 'بانتظار التأكيد']), L3(['Setoran deposit menunggu pembayaran (otomatis)', 'Top-ups awaiting payment (automatic)', 'بانتظار الدفع'])); return out; }); })();
delete A['sd-dep-ok'];
delete A['sd-dep-no'];


/* ======================= CONTROL CENTER DEMO SEED ======================= */
function seedControlCenterData() {
  if (ADMINS.length || APPROVALS.length || AUDIT.length || NOTIFS.length) return;
  AUDIT_SOURCE = 'Web · Control Center';
  ADMINS.push('Anda (Super Admin)', 'Reza — Compliance', 'Maya — Finance Ops', 'Tim Risk');
  const add = (type, o) => APPROVALS.push(Object.assign({ id: 'APR-' + String(19040 + APPROVALS.length * 11), type, domain: AP_TYPES[type][0], status: 'waiting', priority: 'p2', assignee: null, ts: T0 - ri(1, 72) * H, risk: ri(10, 45), docs: [], notes: [], history: [] }, o));
  const tr1 = TRAVELS[1], tr3 = TRAVELS.find(t => t.legal === 'under_review' && t !== tr1) || TRAVELS[5];
  add('legal_doc', { title: 'Perpanjangan izin PPIU — ' + tr1.name, requester: tr1.name, reqRef: tr1.id, reqRoute: '/travel/' + tr1.id + '/legal', priority: 'p1', risk: 34, assignee: ADMINS[1], ts: T0 - 5 * H, docs: [['PDF','SK PPIU Kemenag (perpanjangan).pdf','2,4 MB'],['PDF','Akta perubahan direksi.pdf','1,1 MB'],['JPG','Foto kantor & papan nama.jpg','3,8 MB']], ctx: [['Izin','PPIU'],['Nomor lama','U.412 TAHUN 2021'],['Berlaku s.d. (lama)','14 Okt 2026'],['Paket aktif terdampak','3 paket · 118 jamaah']], diff: null });
  add('withdrawal', { title: 'Withdrawal ' + VENDORS[0].name, requester: VENDORS[0].name, reqRef: VENDORS[0].id, reqRoute: '/vendor', amount: WITHDRAWALS[0].amount, priority: 'p1', risk: 22, assignee: ADMINS[2], ts: T0 - 2 * H, docs: [['PDF','Rekap order 14 transaksi.pdf','380 KB']], ctx: [['Nominal', WITHDRAWALS[0].amount],['Rekening tujuan','Bank Syariah •••• 4471 (terverifikasi)'],['Basis','14 order selesai · 30 hari'],['Saldo tersedia', WITHDRAWALS[0].amount * 1.4]] });
  add('refund', { title: 'Refund ' + (REFUNDS[0] ? REFUNDS[0].booking : 'BK-2641200'), requester: TRAVELERS[8].name, reqRef: REFUNDS[0] && REFUNDS[0].booking, reqRoute: '/booking', amount: REFUNDS[0] ? REFUNDS[0].amount : 36e6, priority: 'p1', risk: 58, ts: T0 - 26 * H, docs: [['PDF','Surat keterangan dokter.pdf','620 KB'],['PDF','Bukti pembayaran VA.pdf','210 KB']], ctx: [['Alasan','Pembatalan jamaah — sakit'],['Kebijakan','Refund 75% (>30 hari sebelum berangkat)'],['Payment','Xendit · VA BSI'],['Flow','VIA_SEGALOKA · dana di ledger']] });
  add('sensitive', { title: 'Perubahan rekening pencairan — ' + TRAVELS[6].name, requester: TRAVELS[6].contact.name, reqRef: TRAVELS[6].id, reqRoute: '/travel/' + TRAVELS[6].id + '/finance', priority: 'p1', risk: 81, ts: T0 - 40 * 60e3, docs: [['PDF','Surat kuasa bermaterai.pdf','540 KB'],['JPG','Buku tabungan.jpg','1,9 MB']], ctx: [['Resource','Travel · rekening settlement'],['Sumber','Web · IP 36.72.x.x (baru)'],['Device','Belum pernah terlihat'],['Login','14 menit sebelum request']], diff: [['Bank','BSI','Bank Muamalat'],['No. rekening','•••• 8812','•••• 0391'],['Atas nama','PT Zamzam Barokah','Zamzam Barokah Travel']] });
  add('travel_verif', { title: 'Verifikasi tenant baru — ' + tr3.name, requester: tr3.name, reqRef: tr3.id, reqRoute: '/travel/' + tr3.id, priority: 'p2', risk: 18, ts: T0 - 20 * H, docs: [['PDF','NIB OSS.pdf','300 KB'],['PDF','NPWP badan.pdf','180 KB'],['PDF','Akta pendirian.pdf','2,2 MB']], ctx: [['Layanan','Umrah, Halal Tour'],['Payment mode diminta','VIA_SEGALOKA'],['Plan','Growth']] });
  add('vendor_verif', { title: 'Verifikasi vendor — ' + VENDORS[2].name, requester: VENDORS[2].name, reqRef: VENDORS[2].id, reqRoute: '/vendor', priority: 'p2', risk: 27, ts: T0 - 30 * H, docs: [['PDF','Commercial registration (CR).pdf','900 KB'],['PDF','Kontrak kerja sama.pdf','1,3 MB']], ctx: [['Kategori','Visa'],['Negara','Arab Saudi'],['Rekomendasi dari','2 Travel aktif']] });
  add('campaign', { title: 'Review campaign — ' + CAMPAIGNS[5].name, requester: CAMPAIGNS[5].owner ? travelById(CAMPAIGNS[5].owner).name : 'Segaloka', reqRef: CAMPAIGNS[5].id, reqRoute: '/ads/campaign/' + CAMPAIGNS[5].id, priority: 'p2', risk: 12, ts: T0 - 9 * H, docs: [['PNG','Creative 1080x1350.png','1,2 MB'],['MP4','Video 15s.mp4','8,4 MB']], ctx: [['Objective','Leads'],['Budget', CAMPAIGNS[5].budget],['Channel', CAMPAIGNS[5].channels.join(', ')],['Klaim sensitif','"Pasti berangkat" — perlu dicek kebijakan iklan']] });
  add('package', { title: 'Publikasi paket — ' + PACKAGES[3].name, requester: travelById(PACKAGES[3].travel).name, reqRef: PACKAGES[3].id, reqRoute: '/marketplace/packages', priority: 'p3', risk: 9, ts: T0 - 50 * H, ctx: [['Harga', PACKAGES[3].price],['Seat', PACKAGES[3].seats],['Keberangkatan','dalam 3 bulan']], docs: [] });
  add('branch', { title: 'Cabang tambahan (ke-3) — ' + TRAVELS[0].name, requester: TRAVELS[0].name, reqRef: TRAVELS[0].id, reqRoute: '/travel/' + TRAVELS[0].id + '/branches', priority: 'p3', risk: 6, ts: T0 - 60 * H, ctx: [['Kuota default','2 cabang'],['Biaya add-on','Rp 450.000 / bulan'],['Status bayar','Invoice terbit, belum dibayar']], docs: [] });
  add('trial', { title: 'Request trial Growth — ' + TRAVELS[20].name, requester: TRAVELS[20].name, reqRef: TRAVELS[20].id, reqRoute: '/travel/' + TRAVELS[20].id + '/subscription', priority: 'p3', risk: 15, ts: T0 - 70 * H, ctx: [['Plan','Growth (14 hari)'],['Catatan','Trial hanya via request']], docs: [] });
  for (let k = 0; k < 10; k++) { const ty = pick(Object.keys(AP_TYPES)); const tr = pick(TRAVELS); add(ty, { title: AP_TYPES[ty][1] + ' — ' + tr.name, requester: tr.name, reqRef: tr.id, reqRoute: '/travel/' + tr.id, priority: wpick(['p1','p2','p3'], [15, 45, 40]), status: wpick(['waiting','in_progress','approved','rejected','needs_revision'], [40, 15, 25, 10, 10]), assignee: rnd() < .6 ? pick(ADMINS) : null, ts: T0 - ri(3, 240) * H, ctx: [['Travel ID', tr.id],['Kota', tr.city]], docs: [['PDF','Lampiran.pdf','400 KB']] }); }
  APPROVALS.forEach(a => { a.history = [{ t: 'Request diajukan oleh ' + a.requester, ts: a.ts, tone: 'info' }, { t: 'Validasi otomatis: format dokumen & kelengkapan ✓', ts: a.ts + 3 * 60e3, tone: 'ok' }]; if (a.assignee) a.history.push({ t: 'Di-assign ke ' + a.assignee, ts: a.ts + 40 * 60e3, tone: 'neu' }); if (['approved','rejected','needs_revision'].includes(a.status)) a.history.push({ t: 'Keputusan: ' + a.status, ts: a.ts + 5 * H, tone: a.status === 'approved' ? 'ok' : a.status === 'rejected' ? 'bad' : 'warn' }); });
  APPROVALS.sort((a, b) => ({ p1: 0, p2: 1, p3: 2 }[a.priority] - { p1: 0, p2: 1, p3: 2 }[b.priority]) || b.ts - a.ts);
  [['Reza — Compliance','legal.verify','Travel/' + TRAVELS[2].id + '/PPIU','success'],['Maya — Finance Ops','withdrawal.approve','Withdrawal/WD-55141','success'],['System','webhook.payment.paid','Payment/' + PAYMENTS[0].id,'success'],['System','settlement.run','Settlement/STL-2609-004','success'],['Anda (Super Admin)','role.update','Role/finance_ops','success'],['Tim Risk','travel.suspend','Travel/' + TRAVELS[9].id,'success'],['System','reconciliation.match','Batch/REC-260923','warning'],['Maya — Finance Ops','refund.reject','Refund/RF-9123','success'],['Unknown','auth.login','User/admin@segaloka','failed'],['Fikri (CS)','conversation.assign','Conversation/CNV-40127','success'],['System','campaign.status','Campaign/' + CAMPAIGNS[7].id + ' → completed','success'],['Anda (Super Admin)','payment_config.update','PaymentRouting/QRIS','success']].forEach(([a, b, c, d], i) => { audit(a, b, c, d, { ts: T0 - (i * 47 + ri(1, 40)) * 60e3, source: a === 'System' ? 'Worker · webhook-consumer' : a === 'Unknown' ? 'Web · IP 103.21.x.x' : 'Web · Control Center', before: b === 'payment_config.update' ? '{ "qris.primary": "DOKU" }' : b === 'role.update' ? '{ "refund.approve": false }' : null, after: b === 'payment_config.update' ? '{ "qris.primary": "Midtrans" }' : b === 'role.update' ? '{ "refund.approve": true }' : null, reason: b === 'travel.suspend' ? 'Subscription suspended & izin PPIU expired' : null }); });
  AUDIT.sort((a, b) => b.ts - a.ts);
  NOTIFS.push(
    { cat: 'approval', tone: 'bad', title: 'Perubahan rekening berisiko tinggi', sub: 'Zamzam Barokah Travel · skor risiko 81', route: '/approval/' + APPROVALS.find(a => a.type === 'sensitive').id, ts: T0 - 38 * 60e3, unread: true },
    { cat: 'payment', tone: 'ok', title: 'Pembayaran dikonfirmasi', sub: PAYMENTS[0].id + ' · ' + PAYMENTS[0].booking, route: '/finance', ts: T0 - 52 * 60e3, unread: true },
    { cat: 'legal', tone: 'warn', title: '6 izin akan expired < 30 hari', sub: 'PPIU & BPW · lihat Legalitas', route: '/travel/legal', ts: T0 - 2 * H, unread: true },
    { cat: 'omnichannel', tone: 'info', title: '3 percakapan melewati SLA', sub: 'Inbox · antrian Unassigned', route: '/omni/inbox', ts: T0 - 3 * H, unread: true },
    { cat: 'settlement', tone: 'bad', title: 'Settlement gagal', sub: SETTLEMENTS[5] ? SETTLEMENTS[5].id + ' · rekening tujuan ditolak bank' : '', route: '/finance', ts: T0 - 5 * H, unread: false },
    { cat: 'ads', tone: 'warn', title: 'Campaign mendekati batas budget', sub: CAMPAIGNS[0].name + ' · 82% terpakai', route: '/ads/campaign/' + CAMPAIGNS[0].id, ts: T0 - 6 * H, unread: false },
    { cat: 'security', tone: 'bad', title: '14 percobaan login gagal', sub: 'admin@segaloka · IP 103.21.x.x · diblokir 30 menit', route: '/compliance/security', ts: T0 - 8 * H, unread: false },
    { cat: 'subscription', tone: 'warn', title: 'Subscription masuk Grace Period', sub: TRAVELS[4].name, route: '/travel/' + TRAVELS[4].id + '/subscription', ts: T0 - 10 * H, unread: false },
    { cat: 'booking', tone: 'info', title: 'Manifest siap diverifikasi', sub: 'Keberangkatan 12 Okt · 44 jamaah', route: '/booking/manifest', ts: T0 - 12 * H, unread: false },
    { cat: 'marketplace', tone: 'neu', title: '4 paket menunggu moderasi', sub: 'Marketplace · Moderasi Produk', route: '/marketplace/moderation', ts: T0 - 20 * H, unread: false }
  );
}
