function navBadge(n) { if (!n.badge) return ''; const v = n.badge(); if (!v) return ''; return `<span class="nbadge ${n.alert ? 'alert' : 'count'}" aria-label="${v} item">${v}</span>`; }
function renderSide() {
  const pws = typeof wsOf === 'function' ? wsOf() : 'admin'; if (pws !== 'admin') { renderPortalSide(pws); return; }
  const act = activeNavId(S.route), an = NAVIDX[act]; const f = S.navFilter.toLowerCase();
  const match = n => !f || t(n.id).toLowerCase().includes(f) || (n.kids || []).some(k => t(k.id).toLowerCase().includes(f));
  let h = `<div class="side-head"><div class="brandmark" style="--brand:${BRAND.color}">${esc(BRAND.mark)}</div><div class="brandtext"><div class="brandname">${esc(BRAND.name)}</div><div class="brandsub">${esc(t('control_center'))}</div></div></div>
  <div class="side-filter">${ic('search', 'sm')}<input id="navfilter" type="search" placeholder="${esc(t('filter_menu'))}" value="${esc(S.navFilter)}" aria-label="${esc(t('filter_menu'))}"></div>
  <nav class="side-scroll" id="sidenav">`;
  NAV.forEach(g => {
    const items = g.items.filter(m => can(m.p) && match(m)); if (!items.length) return;
    const hasActive = items.some(m => m.id === act || (an && an.parent === m));
    const open = f || S.openG.has(g.g) || (hasActive && !S.openG.has('__x' + g.g)); const alertSum = items.reduce((s, m) => s + (m.alert && m.badge ? m.badge() : 0), 0);
    h += `<div class="nav-group"><button class="nav-gbtn" data-act="tg-group" data-g="${g.g}" aria-expanded="${open}"><span class="gl">${esc(t(g.g))}</span>${!open && alertSum ? `<span class="gcount">${alertSum}</span>` : ''}${ic('chevD', 'sm chev')}</button>`;
    if (open) {
      h += `<ul class="nav-list">`;
      items.forEach(m => {
        if (m.kids) {
          const kidAct = an && an.parent === m; const mo = f || S.openM.has(m.id) || (kidAct && !S.openM.has('__x' + m.id)); const kb = m.kids.reduce((s, k) => s + (k.badge ? k.badge() : 0), 0);
          h += `<li><button class="nav-item ${kidAct ? 'parent-active' : ''}" data-act="tg-mod" data-m="${m.id}" aria-expanded="${mo}" data-label="${esc(t(m.id))}" data-fly="${m.id}">${ic(m.i)}<span class="lbl">${esc(t(m.id))}</span>${!mo && kb ? `<span class="nbadge count">${kb}</span>` : ''}${kb ? '<i class="dot"></i>' : ''}${icd('chevR', 'sm chev')}</button>`;
          if (mo) h += `<ul class="nav-sub">${m.kids.filter(k => !f || t(k.id).toLowerCase().includes(f) || t(m.id).toLowerCase().includes(f)).map(k => `<li><a class="nav-item ${k.id === act ? 'active' : ''}" href="#${k.r}" ${k.id === act ? 'aria-current="page"' : ''}><span class="lbl">${esc(t(k.id))}</span>${navBadge(k)}${k.lvl === 'ph' ? `<span class="nbadge soon" title="${esc(t('lvl_ph'))}">IA</span>` : ''}</a></li>`).join('')}</ul>`;
          h += `</li>`;
        } else {
          h += `<li><a class="nav-item ${m.id === act ? 'active' : ''}" href="#${m.r}" data-label="${esc(t(m.id))}" ${m.id === act ? 'aria-current="page"' : ''}>${ic(m.i)}<span class="lbl">${esc(t(m.id))}</span>${navBadge(m)}${m.badge && m.badge() && m.alert ? '<i class="dot"></i>' : ''}${m.lvl === 'ph' ? `<span class="nbadge soon" title="${esc(t('lvl_ph'))}">IA</span>` : ''}</a></li>`;
        }
      });
      h += `</ul>`;
    }
    h += `</div>`;
  });
  h += `</nav><div class="side-foot"><a class="nav-item ${act === 'iamap' ? 'active' : ''}" href="#/ia" data-label="${esc(t('iamap'))}">${ic('grid')}<span class="lbl">${esc(t('iamap'))}</span></a><button class="iconbtn desk-only" style="color:var(--side-ink-2)" data-act="collapse" aria-label="${esc(S.collapsed ? t('expand') : t('collapse'))}" data-label="${esc(S.collapsed ? t('expand') : t('collapse'))}">${ic('panel')}</button></div>`;
  const side = document.getElementById('side'); const sc = side.querySelector('.side-scroll'); const top = sc ? sc.scrollTop : 0; side.innerHTML = h; side.querySelector('.side-scroll').scrollTop = top;
  const fi = document.getElementById('navfilter'); fi.addEventListener('input', e => { S.navFilter = e.target.value; renderSide(); const n = document.getElementById('navfilter'); n.focus(); n.setSelectionRange(n.value.length, n.value.length); });
}


/* ======================= CONTROL CENTER ACTIONS ======================= */
Object.assign(A, {
  /* tables */
  'tbl-f': el => { const T = TBL[el.dataset.tbl]; T.fval = el.dataset.v; T.page = 1; refreshTable(el.dataset.tbl); },
  'tbl-sort': el => { const T = TBL[el.dataset.tbl]; if (T.sortK === el.dataset.k) T.sortDir *= -1; else { T.sortK = el.dataset.k; T.sortDir = 1; } refreshTable(el.dataset.tbl); },
  'tbl-pg': el => { TBL[el.dataset.tbl].page = +el.dataset.p; refreshTable(el.dataset.tbl); document.getElementById('tb-' + el.dataset.tbl).scrollIntoView({ block: 'nearest' }); },
  'tbl-sel': el => { const T = TBL[el.dataset.tbl]; el.checked ? T.sel.add(el.dataset.id) : T.sel.delete(el.dataset.id); refreshTable(el.dataset.tbl); },
  'tbl-selall': el => { const T = TBL[el.dataset.tbl]; const rows = tblRows(el.dataset.tbl).slice((T.page - 1) * T.size, T.page * T.size); rows.forEach(r => el.checked ? T.sel.add(r.id) : T.sel.delete(r.id)); refreshTable(el.dataset.tbl); },
  'tbl-clear': el => { TBL[el.dataset.tbl].sel.clear(); refreshTable(el.dataset.tbl); },
  'tbl-reset': el => { const T = TBL[el.dataset.tbl]; T.q = ''; T.fval = 'all'; T.page = 1; if (el.dataset.tbl === 'travel') Object.keys(TRX).forEach(k => TRX[k] = 'all'); refreshTable(el.dataset.tbl); },
  'tbl-cols': el => { const T = TBL[el.dataset.tbl]; popAt(el, `<div class="menu"><div class="mh">${t('columns')}</div>${T.cols.filter(c => c.k !== 'act').map((c, i) => `<button class="mi" role="menuitemcheckbox" aria-checked="${!T.hidden.has(c.k)}" data-act="tbl-colt" data-tbl="${el.dataset.tbl}" data-k="${c.k}" ${i === 0 ? 'disabled style="opacity:.6"' : ''}>${esc(c.label)}</button>`).join('')}</div>`); },
  'tbl-colt': el => { const T = TBL[el.dataset.tbl]; T.hidden.has(el.dataset.k) ? T.hidden.delete(el.dataset.k) : T.hidden.add(el.dataset.k); el.setAttribute('aria-checked', !T.hidden.has(el.dataset.k)); refreshTable(el.dataset.tbl); },
  bulk: el => { const T = TBL[el.dataset.tbl]; const n = T.sel.size; if (el.dataset.b === 'suspend') { confirmAction({ title: L3(['Suspend ', 'Suspend ', 'تعليق ']) + n + ' Travel', desc: L3(['Tenant tidak dapat menerima booking baru; paket di-unpublish sementara. Booking berjalan tetap dilayani.', 'Tenants cannot receive new bookings; packages are temporarily unpublished. Existing bookings continue.', 'لن تستقبل الشركات حجوزات جديدة.']), tone: 'danger', label: 'Suspend', resource: [...T.sel].join(', '), onOk: r => { [...T.sel].forEach(id => { const x = travelById(id); if (x) { x.op = 'inactive'; audit('Admin Pusat', 'travel.suspend', 'Travel/' + id, 'success', { reason: r }); } }); T.sel.clear(); toast('ok', n + ' Travel suspended', L3(['Tercatat di audit', 'Recorded in audit', 'مسجل']), '/compliance/audit'); rerender(); } }); return; } toast('ok', (el.dataset.b === 'export' ? 'Export ' : L3(['Pengingat dikirim ke ', 'Reminder sent to ', 'أُرسل تذكير إلى '])) + n + ' item', el.dataset.b === 'export' ? L3(['File CSV disiapkan di server — link unduhan dikirim via notifikasi.', 'CSV is prepared server-side — download link sent via notification.', 'يُعد الملف على الخادم.']) : 'WhatsApp + Email'); T.sel.clear(); refreshTable(el.dataset.tbl); },
  export: el => toast('info', 'Export · ' + el.dataset.what, L3(['Export dijalankan di server (menghormati permission & filter aktif). Link dikirim ke Notifikasi.', 'Export runs server-side (respecting permissions & active filters). Link will arrive in Notifications.', 'يتم التصدير على الخادم.'])),
  'more-filter': el => { const sel = (id, k, opts) => `<div class="field"><label for="${id}">${esc(k[1])}</label><select id="${id}">${opts.map(o => `<option value="${esc(o[0])}" ${TRX[k[0]] === o[0] ? 'selected' : ''}>${esc(o[1])}</option>`).join('')}</select></div>`; modal({ title: t('filters_more'), body: `<div class="grid g2" style="gap:10px">${sel('mf-plan', ['plan', 'Plan'], [['all', t('all')], ['Starter', 'Starter'], ['Growth', 'Growth'], ['Scale', 'Scale']])}${sel('mf-legal', ['legal', t('c_legal')], [['all', t('all')], ...['verified', 'expiring', 'under_review', 'expired', 'rejected'].map(s => [s, L3(STATUS[s].slice(2))])])}${sel('mf-pay', ['pay', 'Payment flow'], [['all', t('all')], ['VIA_SEGALOKA', 'VIA_SEGALOKA'], ['DIRECT_TO_TRAVEL', 'DIRECT_TO_TRAVEL']])}${sel('mf-city', ['city', L3(['Kota', 'City', 'المدينة'])], [['all', t('all')], ...CITIES.map(c => [c[0], c[0]])])}</div>`, foot: `<button class="btn ghost" data-act="mf-reset">${t('reset_filters')}</button><span style="flex:1"></span><button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="mf-apply">${L3(['Terapkan', 'Apply', 'تطبيق'])}</button>` }); },
  'mf-apply': () => { TRX.plan = document.getElementById('mf-plan').value; TRX.legal = document.getElementById('mf-legal').value; TRX.pay = document.getElementById('mf-pay').value; TRX.city = document.getElementById('mf-city').value; closeOverlays(); TBL.travel.page = 1; refreshTable('travel'); const n = Object.values(TRX).filter(v => v !== 'all').length; if (n) toast('info', n + ' ' + L3(['filter tambahan aktif', 'extra filters active', 'مرشحات إضافية']), Object.entries(TRX).filter(e => e[1] !== 'all').map(e => e[0] + ': ' + e[1]).join(' · ')); },
  'mf-reset': () => { Object.keys(TRX).forEach(k => TRX[k] = 'all'); closeOverlays(); refreshTable('travel'); },
  'preview-data': () => modal({ title: t('preview'), wide: true, body: `<p class="muted" style="margin-top:0">${L3(['Pratinjau 5 baris pertama sesuai filter aktif — format yang akan diexport.', 'Preview of the first 5 rows under active filters — the export format.', 'معاينة أول 5 صفوف.'])} ${mockmark()}</p><div class="tbl-wrap"><table class="t"><thead><tr>${['travel_id', 'name', 'city', 'licenses', 'legal_status', 'subscription', 'branches', 'payment_flow', 'status'].map(h => `<th class="mono">${h}</th>`).join('')}</tr></thead><tbody>${tblRows('travel').slice(0, 5).map(r => `<tr class="mono" style="font-size:12px"><td>${r.id}</td><td>${esc(r.name)}</td><td>${esc(r.city)}</td><td>${r.lic.map(l => l.type + ':' + l.status).join('|')}</td><td>${r.legal}</td><td>${r.sub.plan}:${r.sub.state}</td><td>${r.branch.used}/${r.branch.quota}</td><td>${r.payMode}</td><td>${r.op}</td></tr>`).join('')}</tbody></table></div>`, foot: `<button class="btn" data-act="close">${t('close')}</button><button class="btn primary" data-act="export" data-what="Travel">${ic('download')}${t('export')}</button>` }),
  'row-menu': el => { const x = travelById(el.dataset.id); popAt(el, `<div class="menu"><div class="mh">${esc(x.name)}</div>${[['eye', t('open_detail'), '/travel/' + x.id], ['filecheck', t('t_legal'), '/travel/' + x.id + '/legal'], ['refresh', t('t_sub'), '/travel/' + x.id + '/subscription'], ['calendar', t('t_book'), '/travel/' + x.id + '/booking'], ['history', t('t_act'), '/travel/' + x.id + '/activity']].map(m => `<button class="mi" data-act="nav" data-r="${m[2]}">${ic(m[0], 'sm')}${esc(m[1])}</button>`).join('')}<div class="sep"></div><button class="mi" data-act="copy" data-v="${x.id}">${ic('copy', 'sm')}Copy Travel ID</button>${can('travel.suspend') ? `<button class="mi" data-act="travel-status" data-id="${x.id}" data-v="${x.op === 'inactive' ? 'active' : 'inactive'}" style="color:var(--${x.op === 'inactive' ? 'ok' : 'bad'})">${ic(x.op === 'inactive' ? 'play' : 'ban', 'sm')}${x.op === 'inactive' ? t('reactivate') : t('suspend')}</button>` : `<button class="mi" aria-disabled="true" style="opacity:.5">${ic('lock', 'sm')}${t('suspend')} · ${t('no_perm_action')}</button>`}</div>`); },
  'add-travel': () => openAddTravel(),
  'add-travel-save': () => { const n = document.getElementById('nt-name').value.trim(); if (!n) { const f = document.getElementById('nt-name'); f.focus(); f.style.borderColor = 'var(--bad)'; return; } const id = 'TRV-' + (12000 + TRAVELS.length * 7); const city = document.getElementById('nt-city').value; const lic = [{ type: 'BPW', no: '—', status: 'draft', exp: T0 + 900 * D }]; if (document.getElementById('nt-u').checked) lic.push({ type: 'PPIU', no: '—', status: 'draft', exp: T0 + 900 * D }); if (document.getElementById('nt-h').checked) lic.push({ type: 'PIHK', no: '—', status: 'draft', exp: T0 + 900 * D }); TRAVELS.unshift({ id, name: n.replace(/^PT\s*/i, ''), city, prov: (CITIES.find(c => c[0] === city) || [])[1], lic, legal: 'under_review', op: 'review', payMode: document.getElementById('nt-pay').value, sub: { plan: document.getElementById('nt-plan').value, state: 'pending', renew: T0 + 30 * D, addonBranch: 0, price: ((PLANS.find(p => p.name === document.getElementById('nt-plan').value) || {}).price || 0) }, branch: { used: 0, quota: 2 }, services: ['Halal Tour'], contact: { name: '—', role: 'Owner', phone: '—', email: '—' }, npwp: '—', nib: '—', joined: nowTs(), gmv30: 0, book30: 0, rating: '—', color: colorFor(n), website: '—' }); audit('Admin Pusat', 'travel.create', 'Travel/' + id, 'success', { after: '{ "status": "draft", "subscription": "pending" }' }); closeOverlays(); toast('ok', L3(['Draft tenant dibuat', 'Tenant draft created', 'أُنشئت المسودة']), n + ' · ' + id + ' · subscription Pending', '/travel/' + id); if (location.hash.includes('?new')) history.replaceState(null, '', '#/travel'); rerender(); },
  /* approval */
  'ap-decide': el => { const a = APPROVALS.find(x => x.id === el.dataset.id); const v = el.dataset.v; confirmAction({ title: ({ approved: t('approve'), rejected: t('reject'), needs_revision: t('revise') })[v] + ' · ' + a.id, desc: esc(a.title), tone: v === 'rejected' ? 'danger' : 'primary', label: ({ approved: t('approve'), rejected: t('reject'), needs_revision: t('revise') })[v], resource: a.reqRef, reason: v !== 'approved' || a.risk >= 60, onOk: r => decideApproval(a.id, v, r) }); },
  'ap-note': el => { const ta = document.getElementById('apnote'); if (!ta.value.trim()) return ta.focus(); const a = APPROVALS.find(x => x.id === el.dataset.id); a.notes.push({ by: 'Admin Pusat', text: ta.value.trim(), ts: nowTs() }); document.getElementById('apdetail').innerHTML = apDetailHTML(a); toast('ok', L3(['Catatan disimpan', 'Note saved', 'حُفظت الملاحظة']), a.id); },
  'ap-back': () => go('/approval'),
  'doc-prev': el => modal({ title: el.dataset.n, body: `<div style="aspect-ratio:1/1.3;max-width:100%;background:var(--surface-2);border:1px solid var(--line);border-radius:8px;display:grid;place-items:center;color:var(--ink-3);text-align:center;padding:20px">${ic('filetext', 'lg')}<div><b>${esc(el.dataset.n)}</b><br>${L3(['Pratinjau dokumen via signed URL (kedaluwarsa 5 menit). Akses tercatat di audit.', 'Document preview via signed URL (expires in 5 min). Access is audited.', 'معاينة عبر رابط موقّع.'])}</div></div>`, foot: `<button class="btn" data-act="close">${t('close')}</button>` }),
  /* travel detail */
  'travel-status': el => { const x = travelById(el.dataset.id); const v = el.dataset.v; confirmAction({ title: (v === 'inactive' ? t('suspend') : t('reactivate')) + ' · ' + x.name, desc: v === 'inactive' ? L3(['Tenant tidak dapat menerima booking baru, paket di-unpublish sementara, website menampilkan status maintenance. Booking & settlement berjalan tetap diproses.', 'The tenant cannot receive new bookings, packages are temporarily unpublished, website shows maintenance. Existing bookings & settlements continue.', 'لن تستقبل الشركة حجوزات جديدة.']) : L3(['Tenant kembali aktif bila legalitas & subscription valid (divalidasi backend).', 'Tenant becomes active again if legality & subscription are valid (validated by backend).', 'تعود الشركة نشطة عند صحة الترخيص.']), tone: v === 'inactive' ? 'danger' : 'primary', resource: x.id, onOk: r => { const prev = x.op; x.op = v; audit('Admin Pusat', v === 'inactive' ? 'travel.suspend' : 'travel.reactivate', 'Travel/' + x.id, 'success', { before: '{ "status": "' + prev + '" }', after: '{ "status": "' + v + '" }', reason: r }); toast(v === 'inactive' ? 'warn' : 'ok', (v === 'inactive' ? 'Suspended · ' : 'Reactivated · ') + x.name, L3(['Tercatat di audit', 'Recorded in audit', 'مسجل']), '/travel/' + x.id + '/activity'); rerender(); } }); },
  'lic-set': el => { const x = travelById(el.dataset.id); const l = x.lic[+el.dataset.i]; const v = el.dataset.v; confirmAction({ title: (v === 'verified' ? L3(['Verifikasi ', 'Verify ', 'توثيق ']) : L3(['Tolak ', 'Reject ', 'رفض '])) + l.type, desc: esc(x.name) + ' · ' + esc(l.no), tone: v === 'verified' ? 'primary' : 'danger', reason: v !== 'verified', resource: x.id + '/' + l.type, onOk: r => { const prev = l.status; l.status = v; if (v === 'verified') l.exp = Math.max(l.exp, T0 + 3 * 365 * D); const has = s => x.lic.some(q => q.status === s); x.legal = has('rejected') ? 'rejected' : has('expired') ? 'expired' : (has('under_review') || has('submitted') || has('draft')) ? 'under_review' : has('expiring') ? 'expiring' : 'verified'; audit('Admin Pusat', 'legal.' + (v === 'verified' ? 'verify' : 'reject'), 'Travel/' + x.id + '/' + l.type, 'success', { before: '{ "status": "' + prev + '" }', after: '{ "status": "' + v + '" }', reason: r }); toast(v === 'verified' ? 'ok' : 'bad', l.type + ' → ' + L3(STATUS[v].slice(2)), x.name + ' · legal: ' + L3(STATUS[x.legal].slice(2))); rerender(); } }); },
  'sens-change': el => { toast('info', L3(['Perubahan sensitif → Approval Center', 'Sensitive change → Approval Center', 'تغيير حساس ← مركز الموافقات']), L3(['Form perubahan akan membuat request dengan before/after diff.', 'The change form creates a request with a before/after diff.', 'يُنشئ طلباً مع الفروقات.']), '/approval'); },
  'add-branch': el => { const x = travelById(el.dataset.id); const over = x.branch.used >= x.branch.quota; modal({ title: L3(['Tambah cabang', 'Add branch', 'إضافة فرع']) + ' · ' + x.name, body: `${over ? `<div class="banner warn" style="border-radius:8px;border:1px solid var(--warn-line);margin-bottom:12px">${ic('alert')}${L3(['Kuota penuh (', 'Quota full (', 'الحصة ممتلئة (']) + x.branch.used + '/' + x.branch.quota + L3([') — cabang ini akan ditagih sebagai add-on Rp 450.000/bulan dan aktif setelah invoice dibayar.', ') — this branch is billed as a Rp 450,000/month add-on and activates after payment.', ') — سيُحتسب كإضافة مدفوعة.'])}</div>` : ''}<div class="field"><label for="nb-name">${L3(['Nama cabang', 'Branch name', 'اسم الفرع'])}</label><input type="text" id="nb-name" value="Cabang ${esc(CITIES[5][0])}"></div><div class="field"><label for="nb-city">${L3(['Kota', 'City', 'المدينة'])}</label><select id="nb-city">${CITIES.map(c => `<option>${c[0]}</option>`).join('')}</select></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="add-branch-ok" data-id="${x.id}">${over ? L3(['Buat invoice add-on', 'Create add-on invoice', 'إنشاء فاتورة']) : t('save')}</button>` }); },
  'add-branch-ok': el => { const x = travelById(el.dataset.id); const over = x.branch.used >= x.branch.quota; const nm = document.getElementById('nb-name').value; if (over) { toast('info', L3(['Invoice add-on diterbitkan', 'Add-on invoice issued', 'صدرت الفاتورة']), nm + ' · ' + L3(['menunggu pembayaran', 'awaiting payment', 'بانتظار الدفع'])); } else { x.branch.used++; BRANCHES.push({ id: x.id.replace('TRV', 'BR') + '-' + x.branch.used, travel: x.id, name: nm, city: document.getElementById('nb-city').value, head: '—', status: 'active', paid: false }); toast('ok', L3(['Cabang ditambahkan', 'Branch added', 'أُضيف الفرع']), nm); } audit('Admin Pusat', 'branch.create', 'Travel/' + x.id, 'success'); closeOverlays(); rerender(); },
  'pkg-set': el => { const p = pkgById(el.dataset.id); const v = el.dataset.v; confirmAction({ title: 'Paket → ' + L3(STATUS[v].slice(2)), desc: esc(p.name) + ' · ' + esc(travelById(p.travel).name), tone: v === 'published' ? 'primary' : 'danger', reason: v !== 'published', resource: p.id, onOk: r => { const prev = p.state; p.state = v; audit('Admin Pusat', 'package.' + v, 'Package/' + p.id, 'success', { before: prev, after: v, reason: r }); toast('ok', p.name + ' → ' + L3(STATUS[v].slice(2)), L3(['Marketplace & website Travel diperbarui realtime', 'Marketplace & Travel website updated in realtime', 'تم التحديث فوراً'])); rerender(); } }); },
  /* omnichannel */
  'omni-tab': el => { OMNI.tab = el.dataset.v; document.querySelectorAll('[data-act="omni-tab"]').forEach(b => b.setAttribute('aria-selected', b === el)); OMNI.drawList(); },
  'omni-back': () => go('/omni/inbox'),
  'ctx-toggle': () => { OMNI.showCtx = !OMNI.showCtx; const o = document.getElementById('omni'); if (o) o.classList.toggle('showctx', OMNI.showCtx); },
  'cv-mode': el => { OMNI.mode = el.dataset.v; const ta = document.getElementById('cv-text'); const v = ta ? ta.value : ''; redrawConv(); const n = document.getElementById('cv-text'); if (n) { n.value = v; n.focus(); } },
  'cv-send': el => sendMsg(el.dataset.id),
  'cv-tpl': el => popAt(el, `<div class="menu" style="max-width:360px"><div class="mh">${t('template')}</div>${TEMPLATES.map((x, i) => `<button class="mi" data-act="cv-tpl-pick" data-i="${i}" style="align-items:flex-start;flex-direction:column;gap:2px"><b>${esc(x[0])}</b><span class="muted" style="font-size:12px;white-space:normal">${esc(x[1].slice(0, 90))}…</span></button>`).join('')}</div>`, 'start'),
  'cv-tpl-pick': el => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const txt = TEMPLATES[+el.dataset.i][1].replace('{nama}', c.contact.split(' ')[0]); closeOverlays(); const ta = document.getElementById('cv-text'); ta.value = txt; ta.focus(); },
  'cv-attach': () => toast('info', L3(['Lampiran', 'Attachment', 'مرفق']), L3(['File diunggah ke storage & dipindai malware sebelum dikirim.', 'Files are uploaded to storage & malware-scanned before sending.', 'يتم الفحص قبل الإرسال.'])),
  'cv-ai': () => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const ta = document.getElementById('cv-text'); ta.value = c.booking ? `Waalaikumsalam ${c.contact.split(' ')[0]}, kami sudah cek booking ${c.booking}. Status saat ini: ${L3(STATUS[bookingById(c.booking).state].slice(2))}. Kami bantu tindak lanjuti hari ini ya.` : `Waalaikumsalam, terima kasih atas minatnya. Untuk paket yang ditanyakan masih tersedia seat. Boleh kami kirimkan detail itinerary & harga?`; ta.focus(); toast('info', 'Segaloka AI', L3(['Draf saran — tinjau sebelum kirim. AI tidak mengirim atas nama Anda.', 'Suggested draft — review before sending. AI never sends on your behalf.', 'مسودة مقترحة — راجعها.'])); },
  'cv-assign': el => { const c = CONVERSATIONS.find(x => x.id === el.dataset.id); popAt(el, `<div class="menu"><div class="mh">Assign</div>${AGENTS.map(a => `<button class="mi" role="menuitemradio" aria-checked="${c.assignee === a.id}" data-act="cv-assign-pick" data-a="${a.id}"><span style="width:7px;height:7px;border-radius:50%;background:${a.online ? 'var(--ok)' : 'var(--ink-3)'}"></span>${esc(a.name)}<span class="muted" style="font-size:11.5px;margin-inline-start:auto">${a.load} open</span></button>`).join('')}<div class="sep"></div><button class="mi" data-act="cv-assign-pick" data-a="">${ic('x', 'sm')}Unassign</button></div>`); },
  'cv-assign-pick': el => { if (!can('omni.assign')) { closeOverlays(); toast('warn', t('no_perm_action'), 'omni.assign'); return; } const c = CONVERSATIONS.find(x => x.id === OMNI.active); c.assignee = el.dataset.a || null; const ag = AGENTS.find(a => a.id === c.assignee); c.messages.push({ dir: 'sys', text: ag ? 'Assigned → ' + ag.name + ' · oleh Admin Pusat' : 'Unassigned · oleh Admin Pusat', ts: nowTs() }); audit('Admin Pusat', 'conversation.assign', 'Conversation/' + c.id, 'success', { after: ag ? ag.name : 'unassigned' }); closeOverlays(); redrawConv(); OMNI.drawList(); toast('ok', ag ? 'Assigned · ' + ag.name : 'Unassigned', c.id); },
  'cv-resolve': el => { const c = CONVERSATIONS.find(x => x.id === el.dataset.id); c.status = 'resolved'; c.resolvedAt = nowTs(); c.unread = 0; c.messages.push({ dir: 'sys', text: 'Resolved · Admin Pusat', ts: nowTs() }); audit('Admin Pusat', 'conversation.resolve', 'Conversation/' + c.id, 'success'); redrawConv(); OMNI.drawList(); toast('ok', 'Resolved · ' + c.contact, L3(['Masuk ke Omnichannel Analytics', 'Counted in Omnichannel Analytics', 'يُحتسب في التحليلات'])); },
  'cv-tag': el => { const c = CONVERSATIONS.find(x => x.id === el.dataset.id); popAt(el, `<div class="menu"><div class="mh">Tag</div>${['Umrah', 'Haji', 'Refund', 'VIP', 'Komplain', 'Reschedule'].map(tg => `<button class="mi" data-act="cv-tag-pick" data-v="${tg}" role="menuitemcheckbox" aria-checked="${c.tags.includes(tg)}">${tg}</button>`).join('')}</div>`); },
  'cv-tag-pick': el => { const c = CONVERSATIONS.find(x => x.id === OMNI.active); const v = el.dataset.v; c.tags.includes(v) ? c.tags.splice(c.tags.indexOf(v), 1) : c.tags.push(v); closeOverlays(); redrawConv(); },
  'toast-demo': el => { if (el.getAttribute('aria-disabled') === 'true') return; toast('info', el.dataset.m, L3(['Simulasi — backend belum terhubung', 'Simulation — backend not connected', 'محاكاة'])); },
  /* ads */
  wizard: () => openWizard(),
  'wz-set': el => { wzCollect(); WZ[el.dataset.f] = el.dataset.v; drawWizard(); },
  'wz-toggle': el => { wzCollect(); const f = el.dataset.f; let v = el.dataset.v; if (f === 'creatives') v = +v; const arr = WZ[f]; arr.includes(v) ? arr.splice(arr.indexOf(v), 1) : arr.push(v); drawWizard(); },
  'wz-go': el => { wzCollect(); WZ.step = Math.max(0, Math.min(WZ_STEPS.length - 1, +el.dataset.v)); drawWizard(); },
  'wz-draft': () => { wzCollect(); if (!(WZ.name || '').trim()) WZ.name = 'Draft ' + fDT(nowTs()); wzCreate('draft'); },
  'wz-submit': () => { wzCollect(); if (!(WZ.name || '').trim()) { WZ.step = 0; drawWizard(); toast('warn', L3(['Nama campaign wajib diisi', 'Campaign name is required', 'الاسم مطلوب']), ''); return; } wzCreate('review'); },
  'camp-set': el => { const c = campById(el.dataset.id); const v = el.dataset.v; const destructive = ['paused', 'completed', 'archived', 'draft'].includes(v); confirmAction({ title: 'Campaign → ' + L3(STATUS[v].slice(2)), desc: esc(c.name), tone: destructive ? 'danger' : 'primary', reason: destructive, resource: c.id, onOk: r => { const prev = c.state; c.state = v;  const ap = APPROVALS.find(a => a.reqRef === c.id && ['waiting', 'in_progress'].includes(a.status)); if (ap && prev === 'review') { ap.status = v === 'scheduled' ? 'approved' : 'rejected'; ap.history.push({ t: 'Diputuskan dari Campaign Detail', ts: nowTs(), tone: v === 'scheduled' ? 'ok' : 'bad' }); } audit('Admin Pusat', 'campaign.status', 'Campaign/' + c.id, 'success', { before: prev, after: v, reason: r }); toast('ok', c.name + ' → ' + L3(STATUS[v].slice(2)), L3(['Status tersinkron ke ad server Segaloka & Analytics', 'Status synced to the Segaloka ad server & Analytics', 'تمت المزامنة'])); rerender(); } }); },
  /* finance */
  'run-recon': () => confirmAction({ title: L3(['Jalankan rekonsiliasi', 'Run reconciliation', 'تشغيل المطابقة']), desc: L3(['Mencocokkan mutasi bank, ledger, dan data gateway untuk 24 jam terakhir. Proses berjalan di background.', 'Matches bank statements, ledger and gateway data for the last 24h. Runs in the background.', 'مطابقة آخر 24 ساعة.']), reason: false, resource: 'REC-260924', onOk: () => { let k = 0; PAYMENTS.forEach(p => { if (p.status === 'paid' && p.recon === 'pending') { p.recon = 'reconciled'; k++; } }); audit('Admin Pusat', 'reconciliation.run', 'Batch/REC-260924', 'success', { after: '{ "matched": ' + k + ' }' }); toast('ok', L3(['Rekonsiliasi selesai', 'Reconciliation complete', 'اكتملت المطابقة']), k + ' matched · ' + PAYMENTS.filter(p => p.recon === 'unmatched' || p.recon === 'mismatch').length + ' ' + L3(['perlu review manual', 'need manual review', 'تحتاج مراجعة']), '/finance/reconciliation'); rerender(); } }),
  'wd-approve': el => { const w = WITHDRAWALS.find(x => x.id === el.dataset.id); confirmAction({ title: 'Approve withdrawal · ' + w.id, desc: esc(w.party) + ' (' + w.partyType + ') · <b>' + money(w.amount, true) + '</b><br>' + esc(w.basis), resource: w.id, reason: w.amount > 50e6, onOk: r => { w.state = 'approved'; audit('Admin Pusat', 'withdrawal.approve', 'Withdrawal/' + w.id, 'success', { before: 'pending', after: 'approved', reason: r }); toast('ok', 'Withdrawal approved · ' + w.id, L3(['Disbursement dijadwalkan oleh payout worker', 'Disbursement scheduled by payout worker', 'تمت جدولة الصرف'])); rerender(); } }); },
  'audit-diff': el => { const a = AUDIT.find(x => x.id === el.dataset.id); drawer({ title: a.action, sub: `<span class="mono">${esc(a.id)}</span>`, body: `<dl class="dl"><dt>Actor</dt><dd>${esc(a.actor)}</dd><dt>Resource</dt><dd class="mono">${esc(a.resource)}</dd><dt>Timestamp</dt><dd>${esc(fDT(a.ts))}</dd><dt>Source</dt><dd>${esc(a.source)}</dd><dt>Result</dt><dd>${esc(a.result)}</dd>${a.reason ? `<dt>${t('reason')}</dt><dd>${esc(a.reason)}</dd>` : ''}</dl><div style="margin-top:14px;border:1px solid var(--line);border-radius:8px;overflow:hidden"><div class="diffrow diffhead" style="grid-template-columns:1fr 1fr"><div>Before</div><div>After</div></div><div class="diffrow" style="grid-template-columns:1fr 1fr"><div class="b mono" style="text-decoration:none">${esc(a.before || '—')}</div><div class="a mono">${esc(a.after || '—')}</div></div></div>` }); },
  'brand-save': el => { if (el.getAttribute('aria-disabled') === 'true') return; const g = i => document.getElementById(i).value; const before = JSON.stringify({ name: BRAND.name, color: BRAND.color }); BRAND.name = g('br-name') || BRAND.name; BRAND.mark = g('br-mark') || BRAND.mark; BRAND.color = g('br-color'); BRAND.legal = g('br-legal'); audit('Admin Pusat', 'brand.update', 'Config/brand', 'success', { before, after: JSON.stringify({ name: BRAND.name, color: BRAND.color }) }); APP.renderSide(); toast('ok', L3(['Brand diperbarui', 'Brand updated', 'تم تحديث الهوية']), L3(['Shell membaca konfigurasi baru tanpa reload', 'Shell picked up the new config without reload', 'دون إعادة تحميل'])); }
});
