/* =============================== PORTAL TRAVEL =============================== */
function trHome() { const tr = me('travel'); const pk = PACKAGES.filter(p => p.travel === tr.id), bk = BOOKINGS.filter(b => b.travel === tr.id), paid = PAYMENTS.filter(p => p.travel === tr.id && p.status === 'paid'); const deps = DEPS.filter(d => d.travel === tr.id).sort((a, b) => a.dep - b.dep);
  const todo = [...tr.lic.filter(l => l.status !== 'verified').map(l => [stTone(l.status), 'filecheck', l.type + ' · ' + L3(STATUS[l.status].slice(2)), L3(['Unggah dokumen perpanjangan', 'Upload renewal documents', 'رفع المستندات']), '/p/travel/legal']), ...(bk.filter(b => b.state === 'awaiting_payment').length ? [['warn', 'card', bk.filter(b => b.state === 'awaiting_payment').length + ' booking ' + L3(['menunggu pembayaran', 'awaiting payment', 'بانتظار الدفع']), L3(['Kirim pengingat ke jamaah', 'Send reminders to pilgrims', 'تذكير']), '/p/travel/bookings']] : []), ...(typeof SD_REQ !== 'undefined' && SD_REQ.filter(r => ['open', 'offered'].includes(r.state) && sdEligible(tr, r) && !SD_OFF.some(o => o.request === r.id && o.travel === tr.id)).length ? [['info', 'tag', SD_REQ.filter(r => ['open', 'offered'].includes(r.state) && sdEligible(tr, r) && !SD_OFF.some(o => o.request === r.id && o.travel === tr.id)).length + ' ' + L3(['permintaan SegaDeals bisa Anda tawar', 'SegaDeals requests you can bid on', 'طلبات SegaDeals']), L3(['Kirim penawaran sebelum permintaan ditutup', 'Send an offer before the request closes', 'أرسل عرضك']), '/p/travel/segadeals']] : []), ...(pk.filter(p => p.state === 'draft').length ? [['neu', 'package', pk.filter(p => p.state === 'draft').length + ' paket draft', L3(['Lengkapi & ajukan review', 'Complete & submit for review', 'أكمل وأرسل']), '/p/travel/packages']] : []), ...(tr.sub.state !== 'active' ? [[stTone(tr.sub.state), 'refresh', 'Subscription · ' + L3(STATUS[tr.sub.state].slice(2)), L3(['Website & listing bergantung subscription aktif', 'Website & listings depend on an active subscription', 'يعتمد على الاشتراك']), '/p/travel/subscription']] : []), ...deps.filter(d => d.dep - nowTs() < 45 * D && d.state !== 'ready').slice(0, 2).map(d => ['info', 'plane', L3(['Manifest belum siap · ', 'Manifest not ready · ', 'الكشف غير جاهز · ']) + d.name, d.pax.filter(p => p.visa !== 'verified').length + ' visa ' + L3(['belum terverifikasi', 'not verified', 'غير موثقة']), '/p/travel/departures'])];
  return `<div class="page">${pHead('travel', tr.name, L3(['Dashboard operasional tenant Travel — paket, booking, keberangkatan, dan keuangan Anda.', 'Travel tenant operations — your packages, bookings, departures and finances.', 'لوحة شركة السفر.']))}
  <div style="display:flex;gap:6px;flex-wrap:wrap;margin:-6px 0 14px">${portalBadge('travel')}<span class="chip mono">${tr.id}</span>${st(tr.op === 'review' ? 'review' : tr.op)}<span class="muted" style="font-size:12px">Legal</span>${st(tr.legal)}<span class="muted" style="font-size:12px">Sub</span>${st(tr.sub.state)}<span class="chip mono">${tr.payMode}</span></div>
  ${kpiRow([{ k: L3(['Booking aktif', 'Active bookings', 'حجوزات نشطة']), v: fN(bk.filter(b => !BK_EXC.includes(b.state) && b.state !== 'completed').length), icon: 'calendar' }, { k: L3(['Jamaah terkonfirmasi', 'Confirmed pilgrims', 'معتمرون مؤكدون']), v: fN(bk.filter(b => ['confirmed', 'processing', 'ready', 'departed'].includes(b.state)).reduce((s, b) => s + b.pax, 0)), icon: 'users' }, { k: L3(['Pembayaran masuk', 'Payments received', 'المدفوعات']), v: money(paid.reduce((s, p) => s + p.amount, 0)), icon: 'wallet' }, { k: L3(['Paket published', 'Published packages', 'باقات منشورة']), v: pk.filter(p => p.state === 'published').length + ' / ' + pk.length, icon: 'package' }])}
  <div class="grid g12" style="margin-top:14px"><div class="c7">${pnl(t('attention'), todo.length ? `<div class="list" style="margin:-14px">${todo.map(a => `<a class="li" href="#${a[4]}"><span class="sev ${a[0]}"></span>${ic(a[1])}<span class="body"><b>${esc(a[2])}</b><span class="sub">${esc(a[3])}</span></span>${icd('chevR', 'sm muted')}</a>`).join('')}</div>` : `<div class="muted">${ic('check', 'sm')} ${L3(['Semua beres.', 'All clear.', 'لا شيء.'])}</div>`, { icon: 'alert' })}</div>
  <div class="c5">${pnl(L3(['Keberangkatan terdekat', 'Upcoming departures', 'الرحلات القادمة']), deps.length ? `<div class="list" style="margin:-14px">${deps.slice(0, 5).map(d => `<a class="li" href="#/p/travel/departures"><span class="body"><b>${esc(d.name)}</b><span class="sub">${d.pax.length} pax · ${rel(d.dep)}</span></span>${st(d.state)}</a>`).join('')}</div>` : stateBlock('empty'), { icon: 'plane' })}</div></div>
  <div style="margin-top:14px">${pnl(L3(['Booking terbaru', 'Latest bookings', 'آخر الحجوزات']), tbl(['Booking', 'Jamaah', L3(['Paket', 'Package', 'الباقة']), 'Total', t('status')], bk.slice(0, 6).map(b => rowLink('/p/travel/bookings/' + b.id, `<td class="mono">${b.id}</td><td>${esc(trvName(b.traveler))} · ${b.pax} pax</td><td>${esc((pkgById(b.pkg) || {}).name)}</td><td class="r tnum">${money(b.total)}</td><td>${st(b.state)}</td>`))), { raw: true, icon: 'calendar', right: `<a class="btn sm ghost" href="#/p/travel/bookings">${t('see_all')}${icd('chevR', 'sm')}</a>` })}</div></div>`; }
route('/p/travel', () => ({ html: trHome() }));
route('/p/travel/packages', () => { const tr = me('travel'); const pk = PACKAGES.filter(p => p.travel === tr.id);
  return { html: `<div class="page">${pHead('travel', L3(['Paket', 'Packages', 'الباقات']), L3(['Buat paket sebagai Draft, lalu ajukan review. Publikasi ke Marketplace dilakukan moderator Segaloka — Travel tidak bisa publish langsung. Kategori mengikuti izin: Umrah→PPIU, Haji→PIHK, Tour/Halal Tour→BPW.', 'Create packages as Draft, then submit for review. Segaloka moderators publish to the Marketplace — Travels cannot publish directly. Category follows licence: Umrah→PPIU, Hajj→PIHK, Tour/Halal Tour→BPW.', 'الباقات.']), `<button class="btn primary" data-act="tp-new">${ic('plus')}${L3(['Buat paket', 'Create package', 'إنشاء باقة'])}</button>`)}
  <section class="panel">${tbl([L3(['Paket', 'Package', 'الباقة']), L3(['Kategori', 'Category', 'الفئة']), 'Harga', L3(['Berangkat', 'Departure', 'المغادرة']), 'Seat', 'Lifecycle', t('action')], pk.map(p => `<tr><td><b>${esc(p.name)}</b><div class="muted mono" style="font-size:11.5px">${p.id}</div></td><td>${p.cat}${licOk(tr, p.cat) ? '' : ` <span class="st warn">${ic('alert')}${licFor[p.cat]}</span>`}</td><td class="r tnum">${money(p.price)}</td><td>${fD(p.dep)}</td><td class="r tnum">${p.sold}/${p.seats}</td><td>${st(p.state)}</td><td class="r"><div class="actions" style="justify-content:flex-end;flex-wrap:nowrap">${({ draft: `<button class="btn sm primary" data-act="tp-set" data-id="${p.id}" data-v="review" ${licOk(tr, p.cat) ? '' : `aria-disabled="true" data-tip="${esc(L3(['Izin ', 'Licence ', 'الترخيص ']) + licFor[p.cat] + L3([' belum terverifikasi', ' not verified', ' غير موثق']))}"`}>${t('submit_review')}</button>`, review: `<button class="btn sm" data-act="tp-set" data-id="${p.id}" data-v="draft">${L3(['Tarik kembali', 'Withdraw', 'سحب'])}</button>`, published: `<button class="btn sm badb" data-act="tp-set" data-id="${p.id}" data-v="unpublished">Unpublish</button>`, unpublished: `<button class="btn sm" data-act="tp-set" data-id="${p.id}" data-v="review">${L3(['Ajukan publish ulang', 'Resubmit', 'إعادة'])}</button>` })[p.state] || ''}</div></td></tr>`), L3(['Belum ada paket', 'No packages yet', 'لا باقات']))}</section></div>` }; });
Object.assign(A, {
  'tp-new': () => { const tr = me('travel'); const cats = ['Umrah', 'Haji', 'Halal Tour', 'Tour'].filter(c => tr.lic.some(l => l.type === licFor[c])); modal({ title: L3(['Buat paket', 'Create package', 'إنشاء باقة']), body: fields([{ k: 'name', label: L3(['Nama paket', 'Package name', 'الاسم']), req: true, def: 'Umrah Reguler 9 Hari' }, { k: 'cat', label: L3(['Kategori (sesuai izin Anda)', 'Category (per your licences)', 'الفئة']), type: 'select', options: cats }, { k: 'price', label: 'Harga / pax (Rp)', type: 'number', req: true, def: 32000000, step: 100000 }, { k: 'seats', label: 'Seat', type: 'number', def: 45, min: 1 }, { k: 'dep', label: L3(['Tanggal berangkat', 'Departure date', 'تاريخ المغادرة']), type: 'date', def: '2026-12-10' }], 'tp-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="tp-save">${L3(['Simpan draft', 'Save draft', 'حفظ مسودة'])}</button>` }); },
  'tp-save': () => { const v = formVals([{ k: 'name', req: true }, { k: 'cat' }, { k: 'price', type: 'number', req: true }, { k: 'seats', type: 'number' }, { k: 'dep' }], 'tp-'); if (!v) return; const tr = me('travel'); const p = { id: uid('PKG'), name: v.name, cat: v.cat, travel: tr.id, price: v.price, seats: v.seats || 45, sold: 0, dep: new Date(v.dep).getTime(), state: 'draft', views30: 0, segadeal: false }; PACKAGES.unshift(p); pAudit('travel', 'package.create', 'Package/' + p.id); closeOverlays(); toast('ok', L3(['Draft paket dibuat', 'Package draft created', 'أُنشئت المسودة']), p.name); rerender(); },
  'tp-set': el => { const p = pkgById(el.dataset.id); const v = el.dataset.v; const prev = p.state; p.state = v; pAudit('travel', 'package.' + (v === 'review' ? 'submit' : v === 'draft' ? 'withdraw' : v), 'Package/' + p.id, { before: prev, after: v }); if (v === 'review') pNotif('marketplace', 'info', L3(['Paket menunggu moderasi', 'Package awaiting moderation', 'باقة بانتظار المراجعة']), p.name + ' · ' + me('travel').name, '/marketplace/moderation'); toast('ok', p.name + ' → ' + L3(STATUS[v].slice(2)), v === 'review' ? L3(['Masuk antrean Moderasi Produk di Control Center', 'Queued in Product Moderation in the Control Center', 'في قائمة المراجعة']) : ''); rerender(); }
});
route('/p/travel/bookings', () => { const tr = me('travel'); const bk = BOOKINGS.filter(b => b.travel === tr.id); return { html: `<div class="page">${pHead('travel', 'Booking', L3(['Semua booking jamaah untuk paket Anda — dari Marketplace, website, Mitra, Agen, Affiliate, dan campaign.', 'All pilgrim bookings for your packages — from Marketplace, website, Partners, Agents, Affiliates and campaigns.', 'الحجوزات.']))}<section class="panel">${defTable('ptb-' + tr.id, Object.assign(bookingTableCfg(() => BOOKINGS.filter(b => b.travel === tr.id)), { route: r => '/p/travel/bookings/' + r.id }))}</section></div>` }; });
const BK_NEXT = { confirmed: ['processing', ['Proses dokumen & visa', 'Process documents & visas', 'معالجة']], processing: ['ready', ['Tandai siap berangkat', 'Mark ready', 'جاهز']], ready: ['departed', ['Berangkat', 'Depart', 'مغادرة']], departed: ['completed', ['Selesaikan perjalanan', 'Complete trip', 'إنهاء']] };
route('/p/travel/bookings/:id', p => { const tr = me('travel'); const b = bookingById(p.id); if (!b || b.travel !== tr.id) return { html: `<div class="page">${stateBlock('noperm', { desc: L3(['Booking ini bukan milik Travel Anda.', 'This booking does not belong to your Travel.', 'ليس لك.']) })}</div>` }; const pays = PAYMENTS.filter(x => x.booking === b.id); const nx = BK_NEXT[b.state]; const exc = BK_EXC.includes(b.state) ? b.state : null;
  return { html: `<div class="page">${phead({ crumbs: [[L3(WS.travel.label), '/p/travel'], ['Booking', '/p/travel/bookings'], [b.id, '']], title: b.id, actions: (nx ? `<button class="btn primary" data-act="tb-next" data-id="${b.id}">${ic('check')}${esc(L3(nx[1]))}</button>` : '') + (['awaiting_payment', 'partially_paid'].includes(b.state) ? `<button class="btn" data-act="tb-remind" data-id="${b.id}">${ic('bell')}${L3(['Kirim pengingat bayar', 'Send payment reminder', 'تذكير'])}</button>` : '') + (!exc && !['departed', 'completed'].includes(b.state) ? `<button class="btn badb" data-act="bk-cancel" data-id="${b.id}">${ic('ban')}${L3(['Batalkan', 'Cancel', 'إلغاء'])}</button>` : '') })}
  <section class="panel" style="padding:12px 14px;margin-bottom:14px">${lifeBar(BK_FLOW, exc ? (b.paid ? 'confirmed' : 'awaiting_payment') : b.state, exc)}</section>
  <div class="grid g2">${pnl('Detail', `<dl class="dl"><dt>Jamaah</dt><dd>${esc(trvName(b.traveler))} · ${b.pax} pax</dd><dt>${L3(['Paket', 'Package', 'الباقة'])}</dt><dd>${esc((pkgById(b.pkg) || {}).name)}</dd><dt>${L3(['Sumber', 'Source', 'المصدر'])}</dt><dd>${esc(b.source)}${b.mitra ? ' · ' + esc((MITRA.find(m => m.id === b.mitra) || {}).name) : ''}${b.agen ? ' → ' + esc((AGEN.find(a => a.id === b.agen) || {}).name) : ''}</dd><dt>Total</dt><dd class="tnum">${money(b.total, true)}</dd><dt>${L3(['Terbayar', 'Paid', 'مدفوع'])}</dt><dd class="tnum">${money(b.paid, true)}</dd></dl>`, { icon: 'info' })}${pnl('Payment', pays.length ? pays.map(x => `<div class="docrow"><span class="fi">${x.channel.split(' ')[0]}</span><span class="body"><b class="mono">${x.id}</b><span>${money(x.amount, true)} · ${x.provider}</span></span>${st(x.status)}</div>`).join('') : '<span class="muted">—</span>', { icon: 'card' })}</div></div>` }; });
Object.assign(A, {
  'tb-next': el => { const b = bookingById(el.dataset.id); const nx = BK_NEXT[b.state]; if (!nx) return; const prev = b.state; b.state = nx[0]; pAudit('travel', 'booking.' + nx[0], 'Booking/' + b.id, { before: prev, after: nx[0] }); toast('ok', 'Booking → ' + L3(STATUS[nx[0]].slice(2)), b.id); rerender(); },
  'tb-remind': el => { const b = bookingById(el.dataset.id); pAudit('travel', 'booking.payment_reminder', 'Booking/' + b.id); toast('ok', L3(['Pengingat terkirim', 'Reminder sent', 'أُرسل التذكير']), trvName(b.traveler) + ' · WhatsApp'); }
});
route('/p/travel/departures', () => { const tr = me('travel'); const deps = DEPS.filter(d => d.travel === tr.id).sort((a, b) => a.dep - b.dep);
  return { html: `<div class="page">${pHead('travel', L3(['Keberangkatan', 'Departures', 'الرحلات']), L3(['Manifest per keberangkatan. Unggah visa jamaah, lalu ajukan verifikasi manifest ke Segaloka.', 'Manifest per departure. Upload pilgrim visas, then submit the manifest for Segaloka verification.', 'الرحلات.']))}${deps.length ? deps.map(d => `<section class="panel" style="margin-bottom:14px"><div class="panel-h"><h3>${ic('plane', 'sm')}${esc(d.name)} <small>${d.pax.length} pax · ${rel(d.dep)}</small></h3>${st(d.state)}${d.state === 'draft' ? `<button class="btn sm primary" data-act="td-submit" data-id="${d.id}">${L3(['Ajukan verifikasi', 'Submit for verification', 'إرسال'])}</button>` : ''}</div>${tbl([L3(['Nama', 'Name', 'الاسم']), 'Booking', L3(['Paspor', 'Passport', 'الجواز']), 'Visa', ''], d.pax.map((p, i) => `<tr><td>${esc(p.name)}</td><td class="mono">${p.booking}</td><td>${st(p.passport)}</td><td>${st(p.visa)}</td><td class="r">${p.visa === 'pending' ? `<button class="btn sm" data-act="td-visa" data-id="${d.id}" data-i="${i}">${ic('upload', 'sm')}${L3(['Unggah visa', 'Upload visa', 'رفع'])}</button>` : ''}</td></tr>`))}</section>`).join('') : `<div class="panel">${stateBlock('empty', { title: L3(['Belum ada keberangkatan', 'No departures yet', 'لا رحلات']) })}</div>`}</div>` }; });
Object.assign(A, {
  'td-visa': el => { const d = DEPS.find(x => x.id === el.dataset.id); const p = d.pax[+el.dataset.i]; p.visa = 'submitted'; pAudit('travel', 'manifest.visa.upload', 'Manifest/' + d.id + '/' + p.id); toast('ok', L3(['Visa diunggah', 'Visa uploaded', 'رُفعت التأشيرة']), p.name + ' · ' + L3(['menunggu verifikasi Segaloka', 'awaiting Segaloka verification', 'بانتظار التحقق'])); rerender(); },
  'td-submit': el => { const d = DEPS.find(x => x.id === el.dataset.id); d.state = 'review'; pAudit('travel', 'manifest.submit', 'Manifest/' + d.id); pNotif('booking', 'info', L3(['Manifest siap diverifikasi', 'Manifest ready for verification', 'كشف جاهز']), d.name + ' · ' + me('travel').name, '/booking/manifest'); toast('ok', L3(['Manifest diajukan', 'Manifest submitted', 'أُرسل الكشف']), d.name); rerender(); }
});
route('/p/travel/mitra', () => { const tr = me('travel'); const ms = MITRA.filter(m => m.travel === tr.id);
  return { html: `<div class="page">${pHead('travel', L3(['Mitra & Agen', 'Partners & Agents', 'الشركاء والوكلاء']), L3(['Mitra Travel hanya terhubung ke Travel Anda. Agen berada di bawah Mitra. Pihak yang menjual untuk banyak Travel memakai role Affiliate.', 'Travel Partners belong only to your Travel. Agents sit under a Partner. Anyone selling for multiple Travels uses the Affiliate role.', 'الهرمية.']), `<button class="btn primary" data-act="tm-new">${ic('plus')}${L3(['Tambah Mitra', 'Add Partner', 'إضافة شريك'])}</button>`)}
  <div class="chain" style="margin-bottom:14px">${[['Travel', tr.name], ['Mitra Travel', ms.length], ['Agen', AGEN.filter(a => a.travel === tr.id).length]].map((n, i, a) => `<div class="cn"><span class="k">${n[0]}</span><span class="v">${esc(n[1])}</span></div>${i < a.length - 1 ? `<span class="ca">${icd('arrowR', 'sm')}</span>` : ''}`).join('')}</div>
  ${ms.length ? ms.map(m => { const ag = AGEN.filter(a => a.mitra === m.id); return `<section class="panel" style="margin-bottom:10px"><div class="panel-h"><h3>${ent(m.name, `<span class="mono">${m.id}</span> · ${esc(m.city)}`, colorFor(m.name))}</h3>${st(m.status)}<button class="btn sm ${m.status === 'active' ? 'badb' : 'okb'}" data-act="tm-toggle" data-id="${m.id}">${m.status === 'active' ? L3(['Nonaktifkan', 'Deactivate', 'تعطيل']) : L3(['Aktifkan', 'Activate', 'تفعيل'])}</button></div><div class="panel-b" style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"><span class="muted" style="font-size:12px">Agen:</span>${ag.length ? ag.map(a => `<span class="chip">${ic('user', 'sm')}${esc(a.name)} ${a.status !== 'active' ? '(' + L3(STATUS[a.status].slice(2)) + ')' : ''}</span>`).join('') : '<span class="muted" style="font-size:12px">—</span>'}<span style="flex:1"></span><span class="muted tnum" style="font-size:12px">${BOOKINGS.filter(b => b.mitra === m.id).length} booking</span></div></section>`; }).join('') : `<div class="panel">${stateBlock('empty')}</div>`}</div>` }; });
Object.assign(A, {
  'tm-new': () => modal({ title: L3(['Tambah Mitra Travel', 'Add Travel Partner', 'إضافة شريك']), body: fields([{ k: 'name', label: L3(['Nama', 'Name', 'الاسم']), req: true }, { k: 'city', label: L3(['Wilayah', 'Area', 'المنطقة']), type: 'select', options: CITIES.map(c => c[0]) }], 'tm-') + `<div class="auditbox">${ic('info')}<span>${L3(['Mitra ini terikat ke ', 'This partner is bound to ', 'مرتبط بـ '])}<b>${esc(me('travel').name)}</b>${L3([' saja (dijaga database).', ' only (enforced by the database).', ' فقط.'])}</span></div>`, foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="tm-save">${t('save')}</button>` }),
  'tm-save': () => { const v = formVals([{ k: 'name', req: true }, { k: 'city' }], 'tm-'); if (!v) return; const m = { id: uid('MTR'), name: v.name, travel: me('travel').id, city: v.city, jamaah30: 0, status: 'active' }; MITRA.unshift(m); pAudit('travel', 'mitra.create', 'Mitra/' + m.id); closeOverlays(); toast('ok', L3(['Mitra ditambahkan', 'Partner added', 'أُضيف الشريك']), m.name); rerender(); },
  'tm-toggle': el => { const m = MITRA.find(x => x.id === el.dataset.id); m.status = m.status === 'active' ? 'inactive' : 'active'; pAudit('travel', 'mitra.' + (m.status === 'active' ? 'activate' : 'deactivate'), 'Mitra/' + m.id); rerender(); }
});
route('/p/travel/finance', () => { const tr = me('travel'); const via = tr.payMode === 'VIA_SEGALOKA'; const wd = WITHDRAWALS.filter(w => w.ref === tr.id); const pays = PAYMENTS.filter(p => p.travel === tr.id);
  return { html: `<div class="page">${pHead('travel', L3(['Keuangan', 'Finance', 'المالية']), via ? L3(['VIA_SEGALOKA: dana jamaah masuk ke ledger Segaloka lalu di-settle T+3. Tarik saldo lewat withdrawal (butuh approval Finance).', 'VIA_SEGALOKA: pilgrim funds go to the Segaloka ledger, settled T+3. Withdraw via a withdrawal request (needs Finance approval).', 'عبر المنصة.']) : L3(['DIRECT_TO_TRAVEL: dana jamaah langsung ke rekening Anda via gateway terintegrasi. Tidak ada saldo di Segaloka.', 'DIRECT_TO_TRAVEL: pilgrim funds go straight to your account via the integrated gateway. No balance is held by Segaloka.', 'مباشر.']), via ? `<button class="btn primary" data-act="wd-req" data-ws="travel">${ic('arrowur')}${L3(['Tarik saldo', 'Withdraw', 'سحب'])}</button>` : '')}
  ${kpiRow([{ k: 'Payment flow', v: `<span class="chip mono" style="font-size:12px">${tr.payMode}</span>` }, { k: L3(['Saldo tersedia', 'Available balance', 'الرصيد']), v: via ? money(tr.balance) : '—' }, { k: L3(['Pembayaran masuk', 'Payments in', 'المدفوعات']), v: money(pays.filter(p => p.status === 'paid').reduce((s, p) => s + p.amount, 0)) }, { k: 'Withdrawal pending', v: fN(wd.filter(w => w.state === 'pending').length) }])}
  <div class="grid g2" style="margin-top:14px">${pnl('Withdrawal', tbl(['ID', 'Amount', t('status'), L3(['Waktu', 'Time', 'الوقت'])], wd.map(w => `<tr><td class="mono">${w.id}</td><td class="r tnum">${money(w.amount, true)}</td><td>${st(w.state)}</td><td>${rel(w.ts)}</td></tr>`)), { raw: true, icon: 'arrowur' })}${pnl('Payment', tbl(['Payment', 'Amount', t('status')], pays.slice(0, 8).map(x => `<tr><td class="mono">${x.id}</td><td class="r tnum">${money(x.amount, true)}</td><td>${st(x.status)}</td></tr>`)), { raw: true, icon: 'card' })}</div></div>` }; });
route('/p/travel/legal', () => { const tr = me('travel'); return { html: `<div class="page">${pHead('travel', L3(['Legalitas', 'Legality', 'الترخيص']), L3(['Izin sesuai layanan. Dokumen perpanjangan diverifikasi tim Compliance Segaloka.', 'Licences per service. Renewal documents are verified by Segaloka Compliance.', 'التراخيص.']))}<section class="panel">${tbl([L3(['Izin', 'Licence', 'الترخيص']), L3(['Nomor', 'Number', 'الرقم']), L3(['Berlaku s.d.', 'Valid until', 'صالح حتى']), t('status'), ''], tr.lic.map((l, i) => `<tr><td><b>${l.type}</b></td><td class="mono">${esc(l.no)}</td><td>${fD(l.exp)} <span class="muted">· ${rel(l.exp)}</span></td><td>${st(l.status)}</td><td class="r">${['verified', 'submitted', 'under_review'].includes(l.status) ? '' : `<button class="btn sm primary" data-act="tl-upload" data-i="${i}">${ic('upload', 'sm')}${L3(['Unggah perpanjangan', 'Upload renewal', 'رفع'])}</button>`}</td></tr>`))}</section></div>` }; });
A['tl-upload'] = el => { const tr = me('travel'); const l = tr.lic[+el.dataset.i]; const inp = document.createElement('input'); inp.type = 'file'; inp.accept = '.pdf,.jpg,.png'; inp.onchange = () => { const f = inp.files[0]; const fname = f ? f.name : l.type + '.pdf'; l.status = 'submitted'; tr.legal = 'under_review'; const a = pApproval({ type: 'legal_doc', domain: 'Legalitas', title: 'Perpanjangan izin ' + l.type + ' — ' + tr.name, requester: tr.name, reqRef: tr.id, reqRoute: '/travel/' + tr.id + '/legal', priority: l.status === 'expired' ? 'p1' : 'p2', docs: [['PDF', fname, f ? fN(Math.round(f.size / 1024)) + ' KB' : '—']], ctx: [['Izin', l.type], ['Nomor lama', l.no]], source: 'Portal Travel' }); pAudit('travel', 'legal.upload', 'Travel/' + tr.id + '/' + l.type, { after: fname }); pNotif('legal', 'warn', L3(['Dokumen legal baru', 'New legal document', 'مستند جديد']), l.type + ' · ' + tr.name, '/approval/' + a.id); toast('ok', L3(['Dokumen diunggah', 'Document uploaded', 'رُفع المستند']), fname + ' → Compliance'); rerender(); }; inp.click(); };
route('/p/travel/subscription', () => { const tr = me('travel'); return { html: `<div class="page">${pHead('travel', 'Subscription', L3(['Subscription dibayar di muka. Default 2 cabang; cabang tambahan berbayar. Trial hanya melalui request.', 'Subscriptions are prepaid. 2 branches by default; extra branches are paid. Trial only by request.', 'الاشتراك.']))}<section class="panel" style="padding:12px 14px;margin-bottom:14px">${lifeBar(['pending', 'active', 'grace', 'suspended', 'expired', 'cancelled'], tr.sub.state === 'trial' ? 'pending' : tr.sub.state)}</section>
  <div class="grid g3">${pnl('Plan', `<div class="kpi" style="padding:0;border:0"><div class="v">${tr.sub.plan}</div><div class="d">${money(tr.sub.price, true)} / bln · ${L3(['perpanjang', 'renews', 'يتجدد'])} ${fD(tr.sub.renew)}</div></div>${['grace', 'suspended', 'expired', 'pending'].includes(tr.sub.state) ? `<button class="btn primary" style="margin-top:12px" data-act="ts-pay">${ic('card')}${L3(['Bayar invoice', 'Pay invoice', 'ادفع الفاتورة'])} · ${money(tr.sub.price)}</button>` : ''}`, { icon: 'refresh' })}${pnl(L3(['Cabang', 'Branches', 'الفروع']), `<div class="kpi" style="padding:0;border:0"><div class="v">${tr.branch.used} / ${tr.branch.quota}</div><div class="d">2 default + ${tr.sub.addonBranch} add-on</div></div><button class="btn" style="margin-top:12px" data-act="ts-branch">${ic('plus')}${L3(['Minta cabang tambahan', 'Request extra branch', 'فرع إضافي'])}</button>`, { icon: 'map' })}${pnl('Trial', `<p class="muted" style="margin:0 0 12px;font-size:12.5px">${L3(['Coba plan lebih tinggi 14 hari — diproses via Approval Center.', 'Try a higher plan for 14 days — processed via the Approval Center.', 'تجربة.'])}</p><button class="btn" data-act="ts-trial" ${tr.sub.plan === 'Scale' ? 'aria-disabled="true" data-tip="Sudah plan tertinggi"' : ''}>${L3(['Request trial', 'Request trial', 'طلب تجربة'])}</button>`, { icon: 'clock' })}</div></div>` }; });
Object.assign(A, {
  'ts-pay': () => { const tr = me('travel'); const prev = tr.sub.state; tr.sub.state = 'active'; tr.sub.renew = nowTs() + 30 * D; if (tr.op === 'inactive' && ['verified', 'expiring'].includes(tr.legal)) tr.op = 'active'; const w = WEBSITES.find(x => x.travel === tr.id); if (w) { w.state = 'published'; w.ssl = 'active'; } pAudit('travel', 'subscription.paid', 'Travel/' + tr.id, { before: prev, after: 'active' }); pNotif('subscription', 'ok', L3(['Subscription dibayar', 'Subscription paid', 'تم الدفع']), tr.name + ' · ' + tr.sub.plan, '/travel/' + tr.id + '/subscription'); toast('ok', L3(['Pembayaran berhasil (sandbox)', 'Payment successful (sandbox)', 'تم الدفع']), 'Subscription → Active · Website published'); rerender(); },
  'ts-branch': () => { const tr = me('travel'); const a = pApproval({ type: 'branch', domain: 'Travel', title: 'Cabang tambahan (ke-' + (tr.branch.quota + 1) + ') — ' + tr.name, requester: tr.name, reqRef: tr.id, reqRoute: '/travel/' + tr.id + '/branches', priority: 'p3', ctx: [['Kuota saat ini', tr.branch.quota + ' cabang'], ['Biaya add-on', 'Rp 450.000 / bulan']], source: 'Portal Travel' }); pAudit('travel', 'branch.request', 'Travel/' + tr.id); pNotif('approval', 'info', L3(['Request cabang tambahan', 'Extra branch request', 'طلب فرع']), tr.name, '/approval/' + a.id); toast('ok', L3(['Request dikirim', 'Request sent', 'أُرسل الطلب']), 'Approval Center'); rerender(); },
  'ts-trial': () => { const tr = me('travel'); const a = pApproval({ type: 'trial', domain: 'SaaS', title: 'Request trial ' + (tr.sub.plan === 'Starter' ? 'Growth' : 'Scale') + ' — ' + tr.name, requester: tr.name, reqRef: tr.id, reqRoute: '/travel/' + tr.id + '/subscription', priority: 'p3', ctx: [['Plan saat ini', tr.sub.plan], ['Durasi', '14 hari']], source: 'Portal Travel' }); pAudit('travel', 'trial.request', 'Travel/' + tr.id); pNotif('subscription', 'info', 'Request trial', tr.name, '/approval/' + a.id); toast('ok', L3(['Request trial dikirim', 'Trial request sent', 'أُرسل']), 'Approval Center'); rerender(); }
});

