/* =============================== PORTAL AFFILIATE =============================== */
route('/p/affiliate', () => { const a = me('affiliate'); const L = REFLINKS.filter(r => r.aff === a.id); const C = COMMISSIONS.filter(c => c.aff === a.id);
  return { html: `<div class="page">${pHead('affiliate', a.name, L3(['Promosikan paket dari banyak Travel sekaligus lewat link & kode referral.', 'Promote packages from many Travels through referral links & codes.', 'المسوّق.']), `<a class="btn primary" href="#/p/affiliate/links">${ic('plus')}${L3(['Buat link', 'Create link', 'إنشاء رابط'])}</a>`)}<div style="display:flex;gap:6px;flex-wrap:wrap;margin:-6px 0 14px">${portalBadge('affiliate')}<span class="chip mono">${a.code}</span>${st(a.status)}<span class="chip">${a.travels.length} Travel</span></div>
  ${kpiRow([{ k: 'Klik', v: fN(L.reduce((s, r) => s + r.clicks, 0)) }, { k: L3(['Konversi', 'Conversions', 'تحويلات']), v: fN(L.reduce((s, r) => s + r.conv, 0)) }, { k: L3(['Komisi disetujui', 'Approved commission', 'عمولة معتمدة']), v: money(C.filter(c => c.state === 'approved').reduce((s, c) => s + c.amount, 0)) }, { k: L3(['Komisi pending', 'Pending commission', 'معلقة']), v: money(C.filter(c => c.state === 'pending').reduce((s, c) => s + c.amount, 0)) }])}
  <div class="grid g12" style="margin-top:14px"><div class="c7">${pnl(L3(['Konversi per hari', 'Conversions per day', 'التحويلات']), barChart(ser().map(d => ({ ts: d.ts, v: BOOKINGS.filter(b => b.aff === a.id && Math.floor(b.created / D) === Math.floor(d.ts / D)).length })), { key: 'v', fmt: v => fN(Math.round(v)) }), { icon: 'bars' })}</div><div class="c5">${pnl(L3(['Per Travel', 'By Travel', 'حسب الشركة']), hbars(L.map(r => [travelById(r.travel).name, r.conv]), v => fN(v) + ' conv'), { icon: 'building' })}</div></div></div>` }; });
route('/p/affiliate/links', () => { const a = me('affiliate'); const L = REFLINKS.filter(r => r.aff === a.id); return { html: `<div class="page">${pHead('affiliate', L3(['Link referral', 'Referral links', 'روابط الإحالة']), L3(['Affiliate boleh punya link ke banyak Travel — berbeda dengan Mitra Travel yang terikat ke satu Travel.', 'Affiliates may link to many Travels — unlike Travel Partners, who are bound to one.', 'روابط.']), `<button class="btn primary" data-act="al-new">${ic('plus')}${L3(['Buat link', 'Create link', 'إنشاء رابط'])}</button>`)}<section class="panel">${tbl(['Travel', 'URL', 'Klik', 'Konversi', t('status'), ''], L.map(r => `<tr><td>${esc(travelById(r.travel).name)}</td><td><span class="mono" style="font-size:11.5px">${esc(r.url)}</span> <button class="btn sm ghost" data-act="copy" data-v="${esc(r.url)}" aria-label="Copy">${ic('copy', 'sm')}</button></td><td class="r tnum">${fN(r.clicks)}</td><td class="r tnum">${r.conv}</td><td>${st(r.state)}</td><td class="r"><button class="btn sm" data-act="al-toggle" data-id="${r.id}">${r.state === 'active' ? t('pause') : t('resume')}</button></td></tr>`))}</section></div>` }; });
Object.assign(A, {
  'al-new': () => { const a = me('affiliate'); modal({ title: L3(['Buat link referral', 'Create referral link', 'إنشاء رابط']), body: fields([{ k: 'travel', label: 'Travel', type: 'select', options: () => TRAVELS.filter(x => x.op === 'active').map(x => [x.id, x.name + (a.travels.includes(x.id) ? ' ✓' : '')]) }], 'al-'), foot: `<button class="btn" data-act="close">${t('cancel')}</button><button class="btn primary" data-act="al-save">${L3(['Buat', 'Create', 'إنشاء'])}</button>` }); },
  'al-save': () => { const a = me('affiliate'); const tid = document.getElementById('al-travel').value; if (REFLINKS.some(r => r.aff === a.id && r.travel === tid)) { toast('info', L3(['Link untuk Travel ini sudah ada', 'Link for this Travel already exists', 'موجود']), ''); closeOverlays(); return; } if (!a.travels.includes(tid)) a.travels.push(tid); const r = { id: uid('REF'), name: a.code + '-' + tid.slice(4), aff: a.id, travel: tid, url: travelById(tid).website + '/?ref=' + a.code, clicks: 0, conv: 0, state: 'active' }; REFLINKS.unshift(r); pAudit('affiliate', 'referral.create', 'ReferralLink/' + r.id); closeOverlays(); toast('ok', L3(['Link dibuat', 'Link created', 'أُنشئ الرابط']), r.url); rerender(); },
  'al-toggle': el => { const r = REFLINKS.find(x => x.id === el.dataset.id); r.state = r.state === 'active' ? 'paused' : 'active'; pAudit('affiliate', 'referral.' + r.state, 'ReferralLink/' + r.id); rerender(); }
});
route('/p/affiliate/commissions', () => { const a = me('affiliate'); const C = COMMISSIONS.filter(c => c.aff === a.id); return { html: `<div class="page">${pHead('affiliate', L3(['Komisi', 'Commission', 'العمولات']), L3(['Komisi dihitung dari booking terbayar dan divalidasi Segaloka.', 'Commission is computed from paid bookings and validated by Segaloka.', 'العمولات.']))}<section class="panel">${tbl(['Booking', 'Travel', 'Rate', 'Komisi', t('status')], C.map(c => `<tr><td class="mono">${c.booking}</td><td>${esc(travelById(c.travel).name)}</td><td class="r tnum">${c.rate}%</td><td class="r tnum">${money(c.amount, true)}</td><td>${st(c.state)}</td></tr>`))}</section></div>` }; });
route('/p/affiliate/payout', () => { const a = me('affiliate'); const ap = COMMISSIONS.filter(c => c.aff === a.id && c.state === 'approved').reduce((s, c) => s + c.amount, 0); const wd = WITHDRAWALS.filter(w => w.ref === a.id); return { html: `<div class="page">${pHead('affiliate', 'Payout', L3(['Komisi yang sudah disetujui dapat dicairkan.', 'Approved commission can be paid out.', 'الصرف.']), `<button class="btn primary" data-act="wd-req" data-ws="affiliate" ${ap > 0 ? '' : `aria-disabled="true" data-tip="${esc(L3(['Belum ada komisi disetujui', 'No approved commission yet', 'لا عمولة']))}"`}>${ic('arrowur')}${L3(['Cairkan', 'Pay out', 'صرف'])} · ${money(ap)}</button>`)}<section class="panel">${tbl(['ID', 'Amount', t('status'), L3(['Waktu', 'Time', 'الوقت'])], wd.map(w => `<tr><td class="mono">${w.id}</td><td class="r tnum">${money(w.amount, true)}</td><td>${st(w.state)}</td><td>${rel(w.ts)}</td></tr>`), L3(['Belum ada payout', 'No payouts yet', 'لا صرف']))}</section></div>` }; });

