/* =============================== APLIKASI PENGGUNA (Traveler) =============================== */
const phone = (inner, tab) => `<div class="phone-wrap"><div class="phone">${inner}<nav class="phone-tabs">${PNAV.traveler.map(([i, l, p]) => `<a href="#/p/traveler${p}" class="${tab === p ? 'on' : ''}">${ic(i)}<span>${esc(L3(l))}</span></a>`).join('')}</nav></div><p class="muted" style="text-align:center;font-size:12px;margin-top:10px">${L3(['Pratinjau aplikasi pengguna (mobile) · data tersambung ke database yang sama', 'Traveler app preview (mobile) · connected to the same database', 'معاينة التطبيق'])}</p></div>`;
let UQ = '', UCAT = 'all';
route('/p/traveler', () => { const u = me('traveler'); const P = PACKAGES.filter(p => p.state === 'published' && (UCAT === 'all' || p.cat === UCAT) && (!UQ || (p.name + travelById(p.travel).name).toLowerCase().includes(UQ.toLowerCase()))); const myReq = SD_REQ.filter(r => r.traveler === u.id && ['open', 'offered'].includes(r.state)); const myOff = SD_OFF.filter(o => o.state === 'sent' && myReq.some(r => r.id === o.request)).length;
  return { html: phone(`<div class="ph-top"><div class="muted" style="font-size:12px">${L3(['Assalamualaikum,', 'Assalamualaikum,', 'السلام عليكم،'])}</div><b style="font-size:17px">${esc(u.name.split(' ')[0])}</b><label class="input" style="width:100%;margin-top:10px;background:#fff;border:0;color:#101828">${ic('search', 'sm')}<input id="u-q" type="search" value="${esc(UQ)}" placeholder="${L3(['Cari paket umrah, haji, tour…', 'Search umrah, hajj, tours…', 'ابحث…'])}"></label></div>
  <div class="ph-body"><div style="display:flex;gap:6px;overflow-x:auto;padding-bottom:4px">${['all', 'Umrah', 'Haji', 'Halal Tour', 'Tour'].map(c => `<button class="fchip" data-act="u-cat" data-v="${c}" aria-pressed="${UCAT === c}">${c === 'all' ? t('all') : c}</button>`).join('')}</div>
  <a class="deal" href="#/p/traveler/segadeals${myReq.length ? '' : '/new'}" style="display:block;margin-top:14px;min-width:0;width:100%"><span class="chip promo">SegaDeals</span><b style="display:block;margin-top:6px">${myReq.length ? (myOff ? myOff + ' ' + L3(['penawaran Travel menunggu Anda', 'Travel offers waiting for you', 'عروض بانتظارك']) : myReq.length + ' ' + L3(['permintaan menunggu penawaran', 'requests awaiting offers', 'طلبات بانتظار العروض'])) : L3(['Belum nemu paket yang pas? Ajukan permintaan', 'Can’t find the right package? Submit a request', 'قدّم طلبك'])}</b><span class="muted" style="font-size:12px">${L3(['Sebutkan tujuan, bulan, jumlah jamaah & budget — Travel berizin yang menawarkan.', 'Tell us destination, month, travellers & budget — licensed Travels make offers.', 'والشركات المرخصة تقدم العروض.'])}</span></a>
  <div class="eyebrow" style="margin:14px 0 6px">${L3(['Paket tersedia', 'Available packages', 'الباقات المتاحة'])} · ${P.length}</div>${P.length ? P.slice(0, 20).map(p => { const tr = travelById(p.travel); return `<a class="ucard" href="#/p/traveler/pkg/${p.id}"><div class="uimg">${esc(p.cat)}</div><div style="flex:1;min-width:0"><b>${esc(p.name)}</b><div class="muted" style="font-size:12px">${esc(tr.name)} ${['verified', 'expiring'].includes(tr.legal) ? `<span style="color:var(--ok)">${ic('shieldc', 'sm')}</span>` : ''}</div><div class="muted" style="font-size:12px">${fD(p.dep)} · ${p.seats - p.sold} seat</div><b class="tnum" style="color:var(--accent-text)">${money(p.price)}</b></div></a>`; }).join('') : stateBlock('noresult')}</div>`, ''), mount() { const q = document.getElementById('u-q'); q.addEventListener('change', () => { UQ = q.value; rerender(); }); } }; });
A['u-cat'] = el => { UCAT = el.dataset.v; rerender(); };
route('/p/traveler/pkg/:id', p => { const pk = pkgById(p.id); if (!pk) return { html: phone(stateBlock('noresult'), '') }; const tr = travelById(pk.travel); const inf = pinfo(pk.id); const deal = null;
  return { html: phone(`<div class="ph-hero"><a href="#/p/traveler" class="iconbtn" style="color:#fff">${icd('chevL')}</a><div><div class="chip" style="background:rgba(255,255,255,.2);color:#fff">${esc(pk.cat)}</div><h2 style="margin:6px 0 0;font-family:var(--font-display)">${esc(pk.name)}</h2></div></div><div class="ph-body">
  <div style="display:flex;justify-content:space-between;align-items:flex-end"><div><div class="muted" style="font-size:12px">${L3(['Mulai dari', 'From', 'ابتداءً من'])}</div><b class="tnum" style="font-size:20px;color:var(--accent-text)">${money(deal ? pk.price * (1 - deal.disc / 100) : pk.price, true)}</b>${deal ? ` <s class="muted tnum" style="font-size:12px">${money(pk.price)}</s>` : ''}</div><span class="chip">${pk.seats - pk.sold} seat</span></div>
  <div class="docrow" style="margin-top:12px">${ent(tr.name, tr.lic.map(l => l.type + (['verified', 'expiring'].includes(l.status) ? ' ✓' : '')).join(' · '), tr.color)}</div>
  <dl class="dl" style="margin:12px 0"><dt>${L3(['Berangkat', 'Departure', 'المغادرة'])}</dt><dd>${fD(pk.dep)}</dd><dt>Hotel Makkah</dt><dd>${esc(inf.hotelMk)}</dd><dt>Hotel Madinah</dt><dd>${esc(inf.hotelMd)}</dd><dt>${L3(['Penerbangan', 'Flight', 'الطيران'])}</dt><dd>${esc(inf.air)}</dd></dl>
  <div class="eyebrow" style="margin-bottom:6px">Itinerary</div><ol style="margin:0;padding-inline-start:20px;font-size:13px;display:grid;gap:4px">${inf.days.map(d => `<li>${esc(d)}</li>`).join('')}</ol>
  <div class="field" style="margin-top:14px"><label for="u-pax">${L3(['Jumlah jamaah', 'Pilgrims', 'عدد المعتمرين'])}</label><input type="number" id="u-pax" value="1" min="1" max="${Math.max(1, pk.seats - pk.sold)}"></div><div class="field" style="margin-top:10px"><label for="u-ref">${L3(['Kode referral (opsional)', 'Referral code (optional)', 'رمز الإحالة'])}</label><input id="u-ref" autocomplete="off" placeholder="${L3(['mis. kode affiliate', 'e.g. affiliate code', 'مثال'])}"></div>
  <button class="btn primary" style="width:100%;justify-content:center;height:44px" data-act="u-book" data-id="${pk.id}" ${pk.seats - pk.sold > 0 ? '' : 'aria-disabled="true" data-tip="Seat habis"'}>${L3(['Pesan sekarang', 'Book now', 'احجز الآن'])}</button></div>`, '') }; });
A['u-book'] = el => { const u = me('traveler'); const pax = +document.getElementById('u-pax').value || 1; const code = ((document.getElementById('u-ref') || {}).value || '').trim().toUpperCase(); const aff = code ? AFFILIATES.find(a => (a.code || '').toUpperCase() === code && a.status !== 'inactive') : null; if (code && !aff) { toast('bad', L3(['Kode referral tidak valid', 'Invalid referral code', 'رمز غير صالح']), code); return; } const pk = pkgById(el.dataset.id); const link = aff ? REFLINKS.find(r => r.aff === aff.id && r.travel === pk.travel) : null; const b = createBooking(el.dataset.id, u.id, pax, aff ? 'Affiliate' : 'Marketplace', aff ? { aff: aff.id, refLink: link ? link.id : null } : null); if (!b) return; if (aff) { const rate = aff.rate != null ? aff.rate : 2.5; COMMISSIONS.unshift({ id: uid('COM'), name: aff.name + ' · ' + b.id, aff: aff.id, booking: b.id, travel: b.travel, rate, amount: Math.round(b.total * rate / 100), state: 'pending', ts: nowTs() }); if (link) link.conv = (link.conv || 0) + 1; pNotif('affiliate', 'ok', L3(['Konversi baru dari kode Anda', 'New conversion from your code', 'تحويل جديد']), b.id + ' · ' + money(b.total), '/p/affiliate'); } audit(u.name, 'booking.create', 'Booking/' + b.id, 'success', { source: 'Aplikasi Pengguna' }); toast('ok', L3(['Booking dibuat', 'Booking created', 'أُنشئ الحجز']), b.id + ' · ' + L3(['bayar DP 30% via VA', 'pay 30% deposit via VA', 'ادفع العربون'])); go('/p/traveler/bookings/' + b.id); };
route('/p/traveler/bookings', () => { const u = me('traveler'); const L = BOOKINGS.filter(b => b.traveler === u.id); return { html: phone(`<div class="ph-top"><b style="font-size:17px">${L3(['Booking saya', 'My bookings', 'حجوزاتي'])}</b></div><div class="ph-body">${L.length ? L.map(b => `<a class="ucard" href="#/p/traveler/bookings/${b.id}"><div style="flex:1;min-width:0"><div style="display:flex;justify-content:space-between;gap:6px"><b class="mono" style="font-size:12.5px">${b.id}</b>${st(b.state)}</div><div style="font-size:13px;margin-top:4px">${esc((pkgById(b.pkg) || {}).name)}</div><div class="muted" style="font-size:12px">${fD(b.dep)} · ${b.pax} pax</div><div class="meter ${b.paid >= b.total ? 'ok' : ''}" style="margin-top:8px"><i style="width:${b.paid / b.total * 100}%"></i></div></div></a>`).join('') : stateBlock('empty', { title: L3(['Belum ada booking', 'No bookings yet', 'لا حجوزات']), cta: `<a class="btn primary sm" href="#/p/traveler">${L3(['Cari paket', 'Find a package', 'ابحث'])}</a>` })}</div>`, '/bookings') }; });
route('/p/traveler/bookings/:id', p => { const u = me('traveler'); const b = bookingById(p.id); if (!b || b.traveler !== u.id) return { html: phone(stateBlock('noperm', { desc: L3(['Booking ini bukan milik Anda.', 'This booking is not yours.', 'ليس لك.']) }), '/bookings') }; const pend = PAYMENTS.find(x => x.booking === b.id && x.status === 'pending'); const due = b.total - b.paid; const exc = BK_EXC.includes(b.state) ? b.state : null;
  return { html: phone(`<div class="ph-top"><a href="#/p/traveler/bookings" style="color:inherit">${icd('chevL', 'sm')}</a> <b class="mono">${b.id}</b></div><div class="ph-body"><div style="display:flex;justify-content:space-between;align-items:center"><b>${esc((pkgById(b.pkg) || {}).name)}</b>${st(b.state)}</div><div class="muted" style="font-size:12px">${esc(travelById(b.travel).name)} · ${fD(b.dep)} · ${b.pax} pax</div>
  <ul class="tl" style="margin-top:14px">${BK_FLOW.slice(1, 7).map(s => { const i = BK_FLOW.indexOf(s), cur = BK_FLOW.indexOf(exc ? 'awaiting_payment' : b.state); return `<li><span class="dotc ${i < cur ? 'ok' : i === cur ? 'info' : ''}"></span><b style="font-weight:${i === cur ? 700 : 500}">${esc(L3(STATUS[s].slice(2)))}</b></li>`; }).join('')}</ul>
  ${due > 0 && !exc ? `<div class="panel" style="padding:12px;margin-top:6px"><div class="eyebrow">${L3(['Pembayaran', 'Payment', 'الدفع'])}</div><div style="display:flex;justify-content:space-between;margin:6px 0"><span>${L3(['Sisa tagihan', 'Balance due', 'المتبقي'])}</span><b class="tnum">${money(due, true)}</b></div>${pend ? `<div class="docrow"><span class="fi">VA</span><span class="body"><b class="mono">8808 ${pend.id.replace(/\D/g, '').slice(-8).padStart(8, '0')}</b><span>${pend.channel} · ${pend.provider} · ${money(pend.amount, true)}</span></span><button class="btn sm ghost" data-act="copy" data-v="8808${pend.id.replace(/\D/g, '').slice(-8)}">${ic('copy', 'sm')}</button></div>` : ''}<button class="btn primary" style="width:100%;justify-content:center;margin-top:8px" data-act="u-pay" data-id="${b.id}">${ic('card')}${L3(['Bayar (simulasi gateway sandbox)', 'Pay (gateway sandbox simulation)', 'ادفع (تجريبي)'])} · ${money(pend ? pend.amount : due)}</button></div>` : ''}
  <div class="panel" style="padding:12px;margin-top:10px"><div class="eyebrow">${L3(['Dokumen', 'Documents', 'المستندات'])}</div><div class="docrow" style="margin-top:6px"><span class="fi">ID</span><span class="body"><b>${L3(['Paspor', 'Passport', 'الجواز'])}</b><span>${L3(STATUS[u.passport].slice(2))}</span></span>${u.passport === 'verified' ? st('verified') : `<button class="btn sm" data-act="u-passport">${ic('upload', 'sm')}${L3(['Unggah', 'Upload', 'رفع'])}</button>`}</div></div>
  <a class="btn" style="width:100%;justify-content:center;margin-top:10px" href="#/p/traveler/chat">${ic('msg')}${L3(['Chat dengan Travel', 'Chat with Travel', 'راسل الشركة'])}</a></div>`, '/bookings') }; });
Object.assign(A, {
  'u-pay': el => { const u = me('traveler'); const b = bookingById(el.dataset.id); let pay = PAYMENTS.find(x => x.booking === b.id && x.status === 'pending'); const due = b.total - b.paid; if (!pay) { pay = { id: uid('PAY'), booking: b.id, travel: b.travel, payer: u.id, amount: due, provider: 'Midtrans', channel: 'QRIS', ref: 'MID-' + Date.now().toString(36).toUpperCase(), status: 'pending', ts: nowTs(), recon: 'pending', flow: b.payMode, fee: 0 }; PAYMENTS.unshift(pay); } pay.status = 'paid'; pay.ts = nowTs(); pay.fee = Math.round(pay.amount * .007); b.paid = Math.min(b.total, b.paid + pay.amount); const prev = b.state; b.state = b.paid >= b.total ? 'confirmed' : 'partially_paid'; audit('System', 'webhook.payment.paid', 'Payment/' + pay.id, 'success', { source: 'Gateway sandbox · ' + pay.provider, before: prev, after: b.state }); pNotif('payment', 'ok', L3(['Pembayaran dikonfirmasi', 'Payment confirmed', 'تم تأكيد الدفع']), pay.id + ' · ' + money(pay.amount) + ' · ' + u.name, '/finance/payment/' + pay.id); if (b.state === 'partially_paid') { PAYMENTS.unshift({ id: uid('PAY'), booking: b.id, travel: b.travel, payer: u.id, amount: b.total - b.paid, provider: pay.provider, channel: pay.channel, ref: pay.ref + '-2', status: 'pending', ts: nowTs(), recon: 'pending', flow: b.payMode, fee: 0 }); } toast('ok', L3(['Pembayaran berhasil', 'Payment successful', 'تم الدفع']), 'Booking → ' + L3(STATUS[b.state].slice(2))); rerender(); },
  'u-passport': () => { const u = me('traveler'); const inp = document.createElement('input'); inp.type = 'file'; inp.accept = 'image/*,.pdf'; inp.onchange = () => { u.passport = 'submitted'; audit(u.name, 'traveler.passport.upload', 'Traveler/' + u.id, 'success', { source: 'Aplikasi Pengguna' }); toast('ok', L3(['Paspor diunggah', 'Passport uploaded', 'رُفع الجواز']), L3(['Menunggu verifikasi Travel', 'Awaiting Travel verification', 'بانتظار التحقق'])); rerender(); }; inp.click(); }
});
route('/p/traveler/chat', () => { const u = me('traveler'); const c = CONVERSATIONS.find(x => x.traveler === u.id);
  return { html: phone(`<div class="ph-top"><b style="font-size:17px">Chat</b><div class="muted" style="font-size:12px">${c ? esc(travelById(c.travel).name) : L3(['Mulai percakapan dengan Travel Anda', 'Start a conversation with your Travel', 'ابدأ المحادثة'])}</div></div><div class="chat" id="uchat" style="min-height:360px;background:var(--surface-2)">${c ? c.messages.filter(m => m.dir !== 'note' && m.dir !== 'sys').map(m => `<div class="msg ${m.dir === 'in' ? 'out' : 'in'}">${esc(m.text)}<div class="mt">${esc(fD(m.ts, { hour: '2-digit', minute: '2-digit' }))}${m.by ? ' · ' + esc(m.by) : ''}</div></div>`).join('') : `<div class="msg sys">${L3(['Belum ada pesan', 'No messages yet', 'لا رسائل'])}</div>`}</div><div class="composer" style="display:flex;gap:6px"><label class="input" style="flex:1;min-width:0"><span class="sr">Pesan</span><input id="u-msg" placeholder="${L3(['Tulis pesan…', 'Write a message…', 'اكتب…'])}"></label><button class="btn primary" data-act="u-send">${icd('send', 'sm')}</button></div>`, '/chat'), mount() { const i = document.getElementById('u-msg'); i.addEventListener('keydown', e => { if (e.key === 'Enter') A['u-send'](); }); const ch = document.getElementById('uchat'); ch.scrollTop = ch.scrollHeight; } }; });
A['u-send'] = () => { const u = me('traveler'); const i = document.getElementById('u-msg'); const v = i.value.trim(); if (!v) return; const mk = maskContact(v); let c = CONVERSATIONS.find(x => x.traveler === u.id && x.channel === 'app' && x.status !== 'closed'); if (!c) { const b = BOOKINGS.find(x => x.traveler === u.id); c = { id: uid('CNV'), channel: 'app', contact: u.name, traveler: u.id, booking: b ? b.id : null, travel: b ? b.travel : null, campaign: null, kind: b ? 'booking' : 'lead', status: 'open', assignee: null, unread: 0, tags: [b ? 'Booking' : 'Lead'], sla: 10, messages: [], ts: nowTs() }; CONVERSATIONS.unshift(c); } c.messages.push({ dir: 'in', text: mk.text, ts: nowTs(), ...(mk.masked ? { masked: mk.masked } : {}) }); c.ts = nowTs(); c.lastIn = nowTs(); c.unread = (c.unread || 0) + 1; if (['resolved', 'closed', 'pending'].includes(c.status)) c.status = 'open'; audit(u.name, 'conversation.message', 'Conversation/' + c.id, 'success', { source: 'Aplikasi Pengguna · Pesan Aplikasi' }); if (mk.masked) toast('warn', L3(['Kontak pribadi disensor', 'Personal contact hidden', 'تم إخفاء جهة الاتصال']), L3(['Demi keamanan, komunikasi & pembayaran tetap di Segaloka.', 'For your safety, communication & payment stay inside Segaloka.', 'للأمان.'])); i.value = ''; rerender(); };
route('/p/traveler/profile', () => { const u = me('traveler'); return { html: phone(`<div class="ph-top" style="text-align:center"><span class="avatar" style="width:56px;height:56px;font-size:18px;margin:0 auto">${esc(initials(u.name))}</span><b style="display:block;font-size:17px;margin-top:8px">${esc(u.name)}</b><span class="muted mono" style="font-size:12px">${u.id}</span></div><div class="ph-body"><dl class="dl"><dt>${L3(['Telepon', 'Phone', 'الهاتف'])}</dt><dd class="mono">${esc(u.phone)}</dd><dt>Email</dt><dd class="mono" style="font-size:12px">${esc(u.email)}</dd><dt>${L3(['Kota', 'City', 'المدينة'])}</dt><dd>${esc(u.city)}</dd><dt>${L3(['Paspor', 'Passport', 'الجواز'])}</dt><dd>${st(u.passport)}</dd><dt>${L3(['Perjalanan', 'Trips', 'الرحلات'])}</dt><dd>${u.trips}</dd></dl>${u.passport !== 'verified' ? `<button class="btn" style="width:100%;justify-content:center;margin-top:12px" data-act="u-passport">${ic('upload')}${L3(['Unggah paspor', 'Upload passport', 'رفع الجواز'])}</button>` : ''}</div>`, '/profile') }; });

